### ISSUE TITLE
[expansion] Childprocess stdout Timestamp

### ISSUE THREAD

**Issue by Boskicl** [Supervisor/supervisor#1436] opened 2021-05-24 15:29 UTC
Hello,

I am curious if these will be an expansion or addition to the stdout format, where the childprocess will also have a timestamp? This will useful for debugging when looking at the supervisor log itself (which does have a timestamp).

**Comment by mnaberez** [comment] 2021-05-24 16:49
Duplicate of #553

**Closed by mnaberez** 2021-05-24 16:49 UTC
Labels: logging
