### ISSUE TITLE
Exit with error if program goes fatal

### ISSUE THREAD

**Issue by mcd-php** [Supervisor/supervisor#733] opened 2016-03-29 09:44 UTC
postgresql + filebeat + cron + supervisord = dead postgresql for whatever error in it, but still live Docker container

Is it possible to gracefully exit with error code and proper messages, if some program goes to fatal state ?

Read docs thoroughly, not found.

**Comment by misakwa** [comment] 2016-06-19 03:24
@mcd-php I was able to achieve something similar by using an event listener as described [here](http://stackoverflow.com/a/37527488). My only issue now is that supervisord exits with status 0 and causes the container to exit with the same status. I was expecting status code > 128 when the listener killed supervisord. Let me know if this works for you.
I'm still not sure if the exit status is a bug in supervisor or not.

**Comment by ankur4u007** [comment] 2016-10-25 15:05
Any update on this, facing the same issue as mentioned by @misakwa

**Comment by OferE** [comment] 2017-04-24 08:08
+1

**Comment by janoszen** [comment] 2017-10-16 10:31
This is actually quite easy to achieve with a little python script:

```
[eventlistener:quit_on_failure]
events=PROCESS_STATE_FATAL
command=/usr/local/bin/manage-supervisord
```

/usr/local/bin/manage-supervisord:
```
#!/usr/bin/python
import sys
import os
import signal

def write_stdout(s):
    sys.stdout.write(s)
    sys.stdout.flush()

def write_stderr(s):
    sys.stderr.write(s)
    sys.stderr.flush()

def main():
    while 1:
        write_stdout('READY\n')
        line = sys.stdin.readline()
        os.kill(1, signal.SIGTERM)
        write_stdout('RESULT 2\nOK')

if __name__ == '__main__':
    main()
    import sys
```

For a complete Docker image doing exactly that, check my repo out: https://github.com/opsbears/docker-supervisord

**Comment by bronger** [comment] 2018-01-18 06:54
In the container world, this is a very typical scenario (i.e. you want an aborting container if anything goes wrong).  Thus, I think a supervisord option like “exit if one program could not be launched” would be very helpful.

**Comment by mnaberez** [comment] 2018-02-23 04:13
Duplicate of #712

**Closed by mnaberez** 2018-02-23 04:13 UTC

**Comment by d10i** [comment] 2021-02-18 10:47
Sorry to write in an old issue but I think this could be useful to others bumping into this problem. @janoszen's script above could be replaced with:
```
[eventlistener:quit_on_failure]
events=PROCESS_STATE_FATAL
command=sh -c 'while true; do echo "READY"; read line; kill -15 1; echo "RESULT 2"; echo "OK"; done'
```

This saves you from having a separate file and from installing Python if you don't need it from anything else.
