### ISSUE TITLE
Merging programs with the same name

### ISSUE THREAD

**Issue by timchenko-a** [Supervisor/supervisor#1542] opened 2022-09-14 08:22 UTC
In case I create 2 programs with the same name, e.g.:
[program:test]
command = /opt/some_script.sh

[program:test]
environment = foo='bar'

What is the expected behaviour of supervisor? In my case (version 3.4.0) both definitions got merged, but I haven't found description of such behaviour in documentation. So I want to understand if this is some kind of expected behaviour and it's reliable to leverage it, or this could be changed without any notice in newer versions.
Thanks

**Comment by mnaberez** [comment] 2022-09-14 16:05
Duplicate of #554

**Closed by mnaberez** 2022-09-14 16:05 UTC
