### ISSUE TITLE
CPU load 100% with NextJS

### ISSUE THREAD

**Issue by markolofsen** [Supervisor/supervisor#1472] opened 2021-11-19 09:38 UTC
Hey!

I am using supervisor to run Next JS in production.
But my CPU loaded until 100%.
Without a supervisor, it is loaded by 0.5%

Why could this happen?

**Comment by mnaberez** [comment] 2021-11-19 17:03
Duplicate of #807

**Closed by mnaberez** 2021-11-19 17:03 UTC
