### ISSUE TITLE
options.py set_rlimits throws KeyError: 'min' if the minprocs or minfds exceeds the allowed limit

### ISSUE THREAD

**Issue by mkmoisen** [Supervisor/supervisor#671] opened 2015-10-08 00:48 UTC
I'm on RHEL and use Supervisor 3.1.3.

This Stackoverflow question has some more context: http://stackoverflow.com/questions/26813434/supervisor-fails-to-start-on-shared-host/33004767#33004767

If either the two conditions are true:
 * the minprocs minprocs configuration is greater than the number of available processes permitted by the system
 * the minfds configuration is greater than the number of file descriptors permitted by the system

Running `supervisord` will result in the following stack trace:

Traceback (most recent call last):
  File "/apps/Python/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.1.3', 'console_scripts', 'supervisord')()
  File "/apps/Python/lib/python2.7/site-packages/supervisor/supervisord.py", line 366, in main
    go(options)
  File "/apps/Python/lib/python2.7/site-packages/supervisor/supervisord.py", line 376, in go
    d.main()
  File "/apps/Python/lib/python2.7/site-packages/supervisor/supervisord.py", line 70, in main
    rlimit_messages = self.options.set_rlimits()
  File "/apps/Python/lib/python2.7/site-packages/supervisor/options.py", line 1316, in set_rlimits
    self.usage(msg % locals())
KeyError: 'min'

The error is in the set_rlimits method of options.py. I think that the %(min)s should be changed to %(lmin)s.

The calling line is 1316: self.usage(msg % locals()). 

There is no local variable 'min', only 'lmin', which is set on line 1298.

**Comment by mnaberez** [comment] 2015-10-08 00:58
Duplicate of #562.  This fix will be released in Supervisor 3.2.

**Closed by mnaberez** 2015-10-08 00:58 UTC
