### ISSUE TITLE
QUESTION: Why does web interface only allow "tail" and "tail -f" for stdout_logfile but no stderr_logfile

### ISSUE THREAD

**Issue by gnanet** [Supervisor/supervisor#1027] opened 2017-12-14 01:09 UTC
This is the first time i am using supervisor, and enabled the web-UI so a semi technical user (minimal shell knowledge but not grep-ing logs, or monitoring things with tail -f) can start and monitor background processes, which were built with logging normal operations to stdout, and problems to stderr.

Then i realized, that the web-UI only allows looking at the stdout logs.

I saw in the docs that over RPC the stderr can be retrieved, so i was looking at the source, to find a solution.

I found out, that the HTTP-interface does respect a **channel** parameter in the **logtail_handler** like **http://supervisor-host:9001/logtail/processname/stderr** 

so it is only a question of displaying the right link for "tail -f err", with only a few lines to replicate tailf [L262](https://github.com/Supervisor/supervisor/blob/master/supervisor/web.py#L262)
-L266 to maybe tailferr in web.py and adding the channel:

```
tailferr = {
        'name':'Tail -f stderr',
        'href':'logtail/%s/stderr' % processname,
        'target':'_blank'
        }
```

This would at least solve one part of my question, the first part (displaing the tail of stderr) would need more changes, by adding a view, decision how it is linked, etc...

So back to the original question: Why is the stderr not available, is this a result of a prior decision? If nothing is against this, and there is a need by others too, i can create a fork to prepare a PR for a possible solution.

**Comment by mnaberez** [comment] 2017-12-14 06:13
Duplicate of #254

**Closed by mnaberez** 2017-12-14 06:13 UTC
Labels: logging, question, web
