### ISSUE TITLE
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist

### ISSUE THREAD

**Issue by One-sixth** [Supervisor/supervisor#1582] opened 2023-03-17 03:13 UTC
I remove all files in /var/log folder, then supervisord can not run again and report this error.
After I manual create this folder /var/log/supervisor.  The supervisor can work again.
I think supervisord should automatically recreate this folder when in need.

Supervisord version is 4.2.5.
System is kali-rolling.

**Comment by mnaberez** [comment] 2023-03-17 03:17
Duplicate of https://github.com/Supervisor/supervisor/issues/120

**Closed by mnaberez** 2023-03-17 03:17 UTC
