### ISSUE TITLE
install fail due to missing  test_requirements.txt

### ISSUE THREAD

**Issue by michaelsalmon** [Supervisor/supervisor#793] opened 2016-07-20 07:31 UTC
I tried to install supervisord 3.3.0 using

python  setup.py install

and it failed dues to a missing test_requirements.txt

I just touched that file and it worked correctly.

My environment is CentOS 6.5, python setuptools 0.6.10-3.el6

It isn't a big deal for me but I thought you should know.

**Comment by mnaberez** [comment] 2016-12-26 17:43
> and it failed dues to a missing test_requirements.txt

Supervisor itself doesn't reference that file anywhere:
```
supervisor$ grep -r test_requirements *
supervisor$
```

> My environment is CentOS 6.5, python setuptools 0.6.10-3.el6

I don't know the cause of the error, but setuptools 0.6.10 is quite old (over 5 years, probably).  This error doesn't seem to occur when installing with recent versions of pip and setuptools, so I'll close this issue for now.  If this is seen again on modern versions, we can reopen.

**Closed by mnaberez** 2016-12-26 17:43 UTC
Labels: packaging
