### ISSUE TITLE
supervisord shouldn't attempt to drop privileges for a non-root user.

### ISSUE THREAD

**Issue by ngton** [Supervisor/supervisor#698] opened 2015-11-19 20:03 UTC
It's impossible to drop privileges for a non-root user.

If I have a supervisord installation that is used by root and non-root users, the configuration must have a user= configuration item.

The problem is that user= results in a CRIT error in the logs. The documentation says user= will do nothing but supervisor is doing something, it's trying to drop privileges when it shouldn't

**Comment by mnaberez** [comment] 2015-11-19 20:12
Duplicate of #695, #697.  I've explained this thoroughly in #695 and and updated the documentation 5bfb2691cd96449c66afdf4a177c5320bcfa9d2b.  Please stop opening new issues.

**Closed by mnaberez** 2015-11-19 20:12 UTC
Labels: logging, question
