### ISSUE TITLE
Option to start process on sequence

### ISSUE THREAD

**Issue by OkenKhuman** [Supervisor/supervisor#1358] opened 2020-07-10 09:22 UTC
I notice an option to delay the staring using `startsecs` but I was looking for option like starting a process after successfully starting another process. Is there a way to do like that?

My requirement was to start a samba client and mount shared directory and then execute a python code from the shared directory as well start a nginx which configuration is in the shared folder.

Please guide me

**Comment by mnaberez** [comment] 2020-07-10 14:05
Duplicate of #122

**Closed by mnaberez** 2020-07-10 14:05 UTC
