### ISSUE TITLE
Tail -f option in the web interface doesn't work

### ISSUE THREAD

**Issue by zcmyworld** [Supervisor/supervisor#704] opened 2015-12-11 07:47 UTC
来自网页 复制
Hi there. I wrote a demo to output string "1" two seconds a time as stdout in Node.js:

setInterval(function(){
      var str = "1";
      console.log(str);
},2000)

In the following both ways, I can successfully see the output:
1. supervisorctl : tail -f 
2. curl 127.0.0.1:9001/log/tail/myprogram

However, as you know, we can access supervisor status from the browser as long as "[inet_http_server]" has been set in the configuration file properly. And, there is also a "tail -f" option in that interface. Unfortunately, it shows nothing when I click into it (the address now is 127.0.0.1:9001/log/tail/myprogram on my laptop).

But if I output "11111....." (the string length is very long) instead, I finally get the output.

How can I see the stdout immediately after I output something (even the string length is short) in the browser?

Thank you.
Kind regards.

**Comment by zcmyworld** [comment] 2015-12-11 07:48
My supervisor version is 3.2.0

**Comment by ngocson2vn** [comment] 2015-12-11 08:55
Please change loglevel in the configuration file as follows:
loglevel=blather

Then, watch log file /tmp/supervisord.log to see error message. If there is any error message, please copy here.

Maybe this is related to https://github.com/Supervisor/supervisor/commit/7e4e41b1f7e955de6d0963972695d6704ebeaf6a

**Comment by zcmyworld** [comment] 2015-12-11 09:45
When I use the browser access http://192.168.59.103:4522/logtail/hello 
(my supervisor program name is "hello")
And the web page still shows nothing.

Thanks a lot!

/tmp/supervisord.log shows:

2015-12-11 09:42:02,892 BLAT write event caused by <supervisor.http.deferring_http_channel connected 192.168.59.3:56393 at 0x7fe78055c950 channel#: 11 requests:1>
2015-12-11 09:42:02,895 BLAT write event caused by <supervisor.http.deferring_http_channel connected 192.168.59.3:56393 at 0x7fe78055c950 channel#: 11 requests:1>
2015-12-11 09:42:03,899 BLAT write event caused by <supervisor.http.deferring_http_channel connected 192.168.59.3:56393 at 0x7fe78055c950 channel#: 11 requests:1>
2015-12-11 09:42:04,117 BLAT read event caused by <supervisor.http.deferring_http_channel connected 192.168.59.3:56393 at 0x7fe78055c950 channel#: 11 requests:1>
2015-12-11 09:42:04,890 BLAT read event caused by <POutputDispatcher at 140632270869640 for <Subprocess at 140632270416496 with name hello in state RUNNING> (stdout)>
2015-12-11 09:42:04,890 DEBG 'hello' stdout output:
1

**Comment by mnaberez** [comment] 2015-12-11 22:04
Duplicate of #149.

**Closed by mnaberez** 2015-12-11 22:04 UTC

**Comment by zcmyworld** [comment] 2015-12-12 13:44
@mnaberez 
Hi, That is a different problem from #149 . #149 has closed in 2012.
But I have used the newest version of supervisor now.
And I still face to the problem.
I had try to use apt-get to install supervisor in ubuntu14.04 and try to install supervisor(version 3.2.0) in ubuntu14.04 form https://pypi.python.org/pypi/supervisor. 
But both of them doesn't work when I use tail -f option in supervisor's web page.
Thanks.

**Comment by mnaberez** [comment] 2015-12-12 15:55
> Hi, That is a different problem from #149 . 

Issue #149 describes the same problem (tail -f on web interface doesn't work).  Please use that issue to discuss this problem.

> #149 has closed in 2012.

#149 is still open.  It was not closed.
