### ISSUE TITLE
Allow usage of supervisor without web ui. This would drop the mandatory dependency to meld3

### ISSUE THREAD

**Issue by palmkevin** [Supervisor/supervisor#665] opened 2015-10-06 09:20 UTC
In my case, I have written my own supervisor control interface using the xmlrpc-API.
I don't use the web-UI shipped with supervisor, but since the ```supervisor_ui_handler``` is always loaded, the third party module ```meld3``` is required.

Could we introduce a possibility the prevent loading of the ```supervisor_ui_handler``` so that supervisor can be used without UI in order to not be obliged to have ```meld3```?
*Loading of  ```supervisor_ui_handler``` is done in the method ```make_http_servers``` (http.py)*

**Comment by mnaberez** [comment] 2015-10-06 15:48
meld3 has been an dependency of Supervisor since 2007.  It's a very small package that is also developed by the Supervisor developers.  It is not going to be removed or made optional.  

This is almost a duplicate of #665.  You've made it clear that you want to strip out the dependencies of Supervisor in order to make it work on your installation, which is nonstandard.  However, these things you want to remove or disable aren't causing problems for other users for many years.  Rather than us adding a bunch of conditional code or hacks to disable parts of Supervisor, which will only benefit one installation using an unsupported installation method, I think it is reasonable to ask that you patch it on your end. Sorry.

**Closed** 2015-10-06 15:48 UTC
Labels: packaging, web
