### ISSUE TITLE
Start and stop processes at the same time

### ISSUE THREAD

**Issue by maxgalbu** [Supervisor/supervisor#966] opened 2017-07-21 11:58 UTC
When I restart using `supervisorctl restart program:*` supervisord waits for every process to stop, waits another 2-3 seconds, then starts processes one by one. 

When I run `supervisorctl update`, the processes are stopped one by one, but are restarted all together.

Is there any way to start the processes all together, with a configuration param? If not, this is a feature request :)

**Comment by FAKERINHEART** [comment] 2017-08-11 14:33
supervisorctl restart all

**Comment by mnaberez** [comment] 2018-02-23 05:08
Duplicate of #723

**Closed by mnaberez** 2018-02-23 05:08 UTC
