### ISSUE TITLE
Web interface buttons redirect to http

### ISSUE THREAD

**Issue by Inkata** [Supervisor/supervisor#1065] opened 2018-03-01 00:44 UTC
Version: 3.3.4

When clicking any of the "refresh" "start all" and "stop all" buttons, the page is redirected.

The HTTP headers sent to the browser assume the http schema

```
Content-Length: 142
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Medusa/1.12
Location: http://b01.example.org:19001/?message=Page%20refreshed%20at%20Wed%20Feb%2028%2018%3A36%3A37%202018
Pragma: no-cache
Cache-Control: no-cache
Date: Thu, 01 Mar 2018 00:36:37 GMT
Content-Type: text/html
```
But this particular page was loaded from https://b01.example.org:19001

The schema can be obtained from the **Referer** header in the http request sent by the browser 

Thanks!

**Comment by mnaberez** [comment] 2018-03-01 01:06
Duplicate of #29 
Duplicate of #251  
Duplicate of #827

**Closed by mnaberez** 2018-03-01 01:06 UTC
Labels: web
