### ISSUE TITLE
Exitting from CTL with ^C

### ISSUE THREAD

**Issue by herhor67** [Supervisor/supervisor#1539] opened 2022-09-10 15:19 UTC
Hello,
There is an issue with quitting the CTL by sending ^C. Usually it works fine, sometimes just needs a while.
But on some occasions it hangs and only an additional ^C will make it die.
```
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1560, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

**Comment by mnaberez** [comment] 2022-09-10 15:58
Duplicate of #236

**Closed by mnaberez** 2022-09-10 15:58 UTC

**Comment by herhor67** [comment] 2022-09-10 16:25
It works fine as an exit of FG mode, it just hangs when exitting the entire CTL... Though I understand if the Ctrl+Z is your "solution" lol.

**Comment by mnaberez** [comment] 2022-09-10 17:17
> Though I understand if the Ctrl+Z is your "solution" lol.

The linked issue is still open.
