### ISSUE TITLE
Hi, Can you add new options in [inet_http_server]

### ISSUE THREAD

**Issue by ivanff** [Supervisor/supervisor#372] opened 2014-02-11 11:38 UTC
For use http proxy, I use nginx:

rewrite ^/supervisor$ /supervisor/ redirect;

location /supervisor/ {
    auth_basic "Restricted Resource";
    auth_basic_user_file  /home/ivan/htpasswd;
....
    proxy_set_header Host $host;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    X-Forwarded-for $remote_addr;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:9001/;
}

But some form posts redirect 301 to /, I fix it write in web.py

def get_server_url(self):
        ...
        server_url += '/supervisor/'
        return server_url

new options like

[inet_http_server]
port = 127.0.0.1:9001
path_info='/supervisor/'

or with change parse option :)
[inet_http_server]
port = 127.0.0.1:9001/supervisor/

What do you think about it, this is usefull?

**Comment by mnaberez** [comment] 2015-02-19 01:36
Closing as a duplicate of #29, which is still open.

**Closed by mnaberez** 2015-02-19 01:36 UTC
Labels: enhancement, web
