### ISSUE TITLE
Location header change domain if behind a proxy server

### ISSUE THREAD

**Issue by krocos** [Supervisor/supervisor#1013] opened 2017-11-06 13:10 UTC
I have the next scheme of proxying:
[proxy] -> [service with supervisor]
And if I call in browser mydomain.com the proxy service do proxy pass to the "supervisor" domain name, and it's ok. But if the supervisor service sends back a Location header I get in browser domain "supervisor" instead of mydomain.com.
I think we need to remove the server_url var here:
https://github.com/Supervisor/supervisor/blob/master/supervisor/web.py#L475

**Comment by krocos** [comment] 2017-11-06 13:24
For example on the refresh action I get back that Location header:
Location: http://supervisor:9001?message=Page%20refreshed%20at%20Mon%20Nov%20%206%2013%3A21%3A06%202017

instead of

Location: /?message=Page%20refreshed%20at%20Mon%20Nov%20%206%2013%3A21%3A06%202017

**Comment by mnaberez** [comment] 2017-11-06 16:46
Duplicate of #29

**Closed by mnaberez** 2017-11-06 16:46 UTC
