### ISSUE TITLE
To manage process state before and after restarting of supervisor

### ISSUE THREAD

**Issue by madhur2928** [Supervisor/supervisor#1411] opened 2021-02-20 10:45 UTC
Hi,

I am facing couple of issues while using supervisor

   1.  While stopping any process using supervisorctl stop, when I restart supervisor that process starts again. My Use case is
        I have "n" of processes running under supervisor
        user can stop any process which is not needed.
        After restarting of supervisor, previous state of supervisor should be maintained. I mean all the services which were stopped/ started should be in that state only.
 
   2.  After reread and update all the services/ processes inside a group gets restarted. Use-case
        There are 5 processes running inside a group
        after adding a new service or modifying any existing service and doing reread/ update, all the services inside that group gets restarted.
        Ideally only edited service should be restarted as happen in case of default program without group

Thanks,
Madhur

**Comment by mnaberez** [comment] 2021-02-22 02:39
Duplicate of #591

**Closed by mnaberez** 2021-02-22 02:39 UTC
