### ISSUE TITLE
Supervisorctl complains there is no sock file

### ISSUE THREAD

**Issue by alanoe** [Supervisor/supervisor#851] opened 2016-11-14 18:06 UTC
I am using supervisor 3.2.0 and I have the following supervisord.conf file:

[unix_http_server]
file=/tmp/supervisor.sock ; (the path to the socket file)

[supervisord]
logfile=/tmp/supervisor.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=2 ; (num of main logfile rotation backups;default 10)
loglevel=info ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisor.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=false ; (start in foreground if true;default false)
minfds=1024 ; (min. avail startup file descriptors;default 1024)
minprocs=200 ; (min. avail process descriptors;default 200)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL for a unix socket

([program] sections ....]

I start supervisor server using

$ supervisord -c supervisord.conf

and then try to get the status of a program using

$ supervisorctl -c supervisord.conf status <program_name>
unix:///tmp/supervisor.sock no such file

Shouldn't the socket file be created automatically by supervisor?

**Comment by FAKERINHEART** [comment] 2016-11-21 01:55
Please check your permission to the file. Is there any file with same name you have permission to delete?

**Comment by mnaberez** [comment] 2016-11-25 17:29
> Shouldn't the socket file be created automatically by supervisor?

Here is what I tried to reproduce this. 

Check that the socket file does not already exist:
```
$ ls /tmp/*.sock
ls: cannot access '/tmp/*.sock': No such file or directory
```

Start `supervisord` in the foreground with a socket file `/tmp/supervisor.sock`:

```
$ cat supervisord.conf
[supervisord]
loglevel=info

[unix_http_server]
file=/tmp/supervisor.sock

$ supervisord --version
3.3.1

$ supervisord -n -c supervisord.conf
2016-11-25 09:17:39,273 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-11-25 09:17:39,273 INFO supervisord started with pid 2604
```

While `supervisord` is still running, check for the socket file in another terminal:

```
$ ls /tmp/*.sock
/tmp/supervisor.sock
```

This is using Supervisor 3.3.1 but there weren't any changes in socket file creation for many versions.  I'm going to close this for now, but if you can provide instructions that will reproduce your report then we can reopen.

**Closed by mnaberez** 2016-11-25 17:29 UTC
Labels: supervisorctl

**Comment by joaodlf** [comment] 2017-10-26 09:25
Silly question, I have limited understanding over unix/linux, but won't the socket file be cleared every  once in a while since it's being generated in /tmp ?

I run supervisor in many VMs, and every once in a while I will get this exact same issue. Doing a `systemctl status supervisord.service` shows everything is running correctly, but a `supervisorctl restart analytics_processor` will fail with a "unix:///tmp/supervisor.sock no such file".

This s very sporadic, which leads me to believe it's an issue with placing the file in /tmp.

Any insights over this?

**Comment by mnaberez** [comment] 2017-10-26 14:58
> This s very sporadic, which leads me to believe it's an issue with placing the file in /tmp.
>
> Any insights over this?

Put it somewhere else.  `/tmp` is only used as an example since it's available on all systems.

**Comment by lestortues67** [comment] 2019-02-20 14:11
Supervisor or supervisord is really JUNK ! ! ! !

**Comment by alanoe** [comment] 2020-04-08 23:56
> Put it somewhere else. /tmp is only used as an example since it's available on all systems.

It'd be nice to document this suggestion somewhere as it is not obvious (IMHO).

Sorry for the really late answer.
