### ISSUE TITLE
plugins not loading

### ISSUE THREAD

**Issue by strangereon** [Supervisor/supervisor#1181] opened 2018-12-12 15:35 UTC
I'm unable to get plugins to load in supervisor.  I'm trying to load the wildcards plugin and can't get the commands to show up.

I'm running on Ubuntu 14.04 with supervisor(3.3.4) and supervisor-wildcards(0.1.3) installed via pip using python 2.7.6

I've added the following to the supervisor config that i pass as the -c parameter when starting supervisord:

[ctlplugin:wildcards]
supervisor.ctl_factory = supervisorwildcards.controllerplugin:make_wildcards_controllerplugin

I successfully tested importing supervisorwildcards in a python shell.

Am I missing something?

**Comment by mnaberez** [comment] 2019-04-07 22:08
Here's what I tried to reproduce this.

```
$ pip install supervisor supervisor-wildcards
...

$ supervisord --version 
4.0.0

$ cat supervisord.conf 
[supervisorctl]

[ctlplugin:wildcards]
supervisor.ctl_factory = supervisorwildcards.controllerplugin:make_wildcards_controllerplugin

$ supervisorctl -c supervisord.conf help

default commands (type help <topic>):
=====================================
add    exit      open  reload  restart   start   tail   
avail  fg        pid   remove  shutdown  status  update 
clear  maintail  quit  reread  signal    stop    version

wildcards commands (type help <topic>):
=======================================
mrestart  mstart  mstop
```

Since I am unable to duplicate this, I am going to close this issue.  If you can provide more details to reproduce it, we can reopen.

**Closed by mnaberez** 2019-04-07 22:08 UTC
Labels: supervisorctl
