### ISSUE TITLE
Way to control output of supervisord process

### ISSUE THREAD

**Issue by bhavin192** [Supervisor/supervisor#1152] opened 2018-09-21 13:27 UTC
It will be better if we can control how `supervisord` logs things to it's `stdout`. AFAIK there is not way to do that as of now. It will be helpful when using supervisord inside container. Like ability to just show `stdout` and `stderr` of child processes and suppressing supervisord's own logs.

**Comment by mnaberez** [comment] 2018-09-24 00:15
Duplicate of #661

**Closed by mnaberez** 2018-09-24 00:15 UTC
Labels: logging
