### ISSUE TITLE
supervisord.conf - working configuration of GNOME

### ISSUE THREAD

**Issue by D3vil0p3r** [Supervisor/supervisor#1575] opened 2023-02-21 22:43 UTC
Hello,
I know this is not an issue but a question. I tried to test several configuration of supervisor with GNOME for an Arch Linux docker container but I failed on configuring it because on supervisor logs GNOME does not run.

What is the current working configuration to implement in `supervisord.conf` file for running GNOME session?

Are external additional files needed?

Thank you in advance and sorry for the question.

**Comment by mnaberez** [comment] 2023-02-22 00:36
> What is the current working configuration to implement in supervisord.conf file for running GNOME session?

I don't think anyone working on Supervisor has run GNOME under it or knows if it is possible.

I'll leave this question open for a while, hopefully someone from the community can help.

**Comment by D3vil0p3r** [comment] 2023-02-22 15:40
> > What is the current working configuration to implement in supervisord.conf file for running GNOME session?
> 
> I don't think anyone working on Supervisor has run GNOME under it or knows if it is possible.
> 
> I'll leave this question open for a while, hopefully someone from the community can help.

Thank you mate. I hope someone has GNOME configuration because it could be very nice to use by supervisor, for GNOME users like me.

**Comment by mnaberez** [comment] 2024-11-29 18:16
Closing this issue because the Supervisor developers don't have enough bandwidth to assist with setting up individual programs or systems. If someone can help with a sample configuration for this use case, please feel free to post it below even if the issue is closed.

**Closed by mnaberez** 2024-11-29 18:16 UTC
Labels: question
