### ISSUE TITLE
Still: Error: supervisor_quick:make_quick_controllerplugin cannot be resolved within [ctlplugin:quick].

### ISSUE THREAD

**Issue by Khadmi** [Supervisor/supervisor#1421] opened 2021-03-18 06:38 UTC
@mnaberez  Thanks for your reply,
I have tried the above but still having same issue , i am also attaching logs.

Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import supervisor
>>> import supervisor_quick 

sudo supervisorctl status
Error: supervisor_quick:make_quick_controllerplugin cannot be resolved within [ctlplugin:quick].

_Originally posted by @Khadmi in https://github.com/Supervisor/supervisor/issues/1420#issuecomment-801643592_

**Comment by mnaberez** [comment] 2021-03-18 15:24
Duplicate of #1420

**Closed by mnaberez** 2021-03-18 15:24 UTC
