### ISSUE TITLE
xmlrpc stuck on stop on version 3.0b2

### ISSUE THREAD

**Issue by boazin** [Supervisor/supervisor#861] opened 2016-12-10 09:06 UTC
I have a problem that happens rarely on production - but finally it got recreated in a manual supervisorctl so I have a traceback.

The version is 3.0b2 (default ubuntu 14.04 version).
I'd appreciate if someone can assist - at least in verifying that getting out of the default ubuntu version and upgrading will solve the problem:

```
$ sudo supervisorctl restart <running name>
# <hangs forever>

^C

Traceback (most recent call last):
  File "/usr/bin/supervisorctl", line 9, in <module>
    load_entry_point('supervisor==3.0b2', 'console_scripts', 'supervisorctl')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py", line 1116, in main
    c.onecmd(" ".join(options.args))
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py", line 144, in onecmd
    return do_func(arg)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py", line 758, in do_restart
    self.do_stop(arg)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py", line 732, in do_stop
    result = supervisor.stopProcess(name)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 462, in request
    r = self.connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize) 
KeyboardInterrupt
```

**Comment by mnaberez** [comment] 2016-12-10 17:24
The traceback from `supervisorctl` just shows it waiting on a response from `supervisord`, which could be normal.  `supervisord` blocks the response until the process shuts down.  One way it can hang for a long time is if the `stopwaitsecs` option in the config file is set to a large value.  In order to do more troubleshooting, we'd need to see what `supervisord` is doing at the time it is not responding (e.g. with `strace`, or with `supervisord --loglevel=trace`).

> The version is 3.0b2 (default ubuntu 14.04 version).
I'd appreciate if someone can assist - at least in verifying that getting out of the default ubuntu version and upgrading will solve the problem:

Since we don't know what the problem is, if any, we can't say if upgrading to a more recent version will make a difference.  Supervisor 3.0b2 is over [3 years old](https://github.com/Supervisor/supervisor/blob/3.3.1/CHANGES.txt).  The changelog shows many fixes since 3.0b2, so it's probably a good idea.

I'm going to close this issue for now since I don't see anything we can do here.  If you can reproduce this on a more recent version, we can reopen.

**Closed by mnaberez** 2016-12-10 17:24 UTC
Labels: xmlrpc
