### ISSUE TITLE
Install docs should prefer `pip` over `easy_install`

### ISSUE THREAD

**Issue by jeffwidman** [Supervisor/supervisor#831] opened 2016-09-30 16:51 UTC
For all the reasons enumerated here: http://stackoverflow.com/questions/3220404/why-use-pip-over-easy-install

http://supervisord.org/installing.html should have the `pip` instructions at the top. I'd actually prefer to remove the `easy_install` instructions altogether.

We did the same thing over in `Flask`: https://github.com/pallets/flask/issues/1919

I can submit a PR if this is something the maintainers are open to.

**Comment by mnaberez** [comment] 2016-09-30 16:53
Duplicate of #623.

**Closed by mnaberez** 2016-09-30 16:53 UTC
Labels: packaging
