### ISSUE TITLE
How to pass custom variables

### ISSUE THREAD

**Issue by BytesPirate** [Supervisor/supervisor#1638] opened 2024-04-01 06:17 UTC
I'd like to customize some of the variables passed in, which doesn't seem to be supported，My files are as follows：

```ini
[setting:variables]
server_port=
;server_host=
server_prod=test
server_user=nginx
dir=
job_name=
module_name=

[usage:java]
java_home=/usr/local/jdk8/bin/java -jar
java_memory=-Xms256m -Xmx256m -XX:MaxMetaspaceSize=256M
springboot_options=-Dspring.profiles.active=%(server_prod)s
java_path=%(setting:variables:dir)s/content/%(setting:variables:job_name)s/%(setting:variables:module_name)s.jar

[monitor:jmx]
jmx_start=-Dcom.sun.management.jmxremote
jmx_host=-Djava.rmi.server.hostname=%(server_host)s
jmx_port=-Dcom.sun.management.jmxremote.port=1%(server_port)s
jmx_rmi_port=-Dcom.sun.management.jmxremote.rmi.port=1%(server_port)s
jmx_ssl=-Dcom.sun.management.jmxremote.ssl=false
jmx_auth=-Dcom.sun.management.jmxremote.authenticate=false

[program:%(setting:variables:job_name)s-%(setting:variables:module_name)s]
command=%(usage:java:java_home)s \
        %(usage:java:java_memory)s \
        %(usage:java:springboot_options)s \
        %(usage:java:java_path)s \
;        %(monitor:jmx:jmx_start)s \
;        %(monitor:jmx:jmx_host)s \
;        %(monitor:jmx:jmx_port)s \
;        %(monitor:jmx:jmx_rmi_port)s \
;        %(monitor:jmx:jmx_ssl)s \
;        %(monitor:jmx:jmx_auth)s \
autostart=true
autorestart=true
startsecs=10
startretries=3
user=%(setting:variables:server_user)s
priority=999
redirect_stderr=true
stopasgroup=false
killasgroup=false
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=20
stdout_logfile=%(setting:variables:dir)s/logs/%(setting:variables:job_name)s/%(setting:variables:module_name)s.log
```

Is it a mistake in my code or something else, thanks for letting me know!

**Comment by mnaberez** [comment] 2024-04-01 16:02
Duplicate of #1058

**Closed by mnaberez** 2024-04-01 16:02 UTC
