### ISSUE TITLE
supervisorctl (re)start should exit 1 on process error

### ISSUE THREAD

**Issue by kerma** [Supervisor/supervisor#886] opened 2017-02-07 15:03 UTC
$ supervisorctl restart myservice
    myservice: ERROR (no such process)
    $ echo $?
    0
    $ supervisorctl restart myservice2
    myservice2: ERROR (spawn error)
    $ echo $?
    0

This makes life really hard for automated processes. I need to parse the ctl output to figure out whether my service was successfully (re)started. 

Please make (re)start to exit 1 on process error or add an optional `--strict` flag or similar to force this behaviour (in case the are valid reasons why one should consider failed restart a success)

**Comment by mnaberez** [comment] 2017-02-07 16:39
Duplicate of #24.

**Closed by mnaberez** 2017-02-07 16:39 UTC
Labels: supervisorctl
