### ISSUE TITLE
`ERROR (no such file)` could give more information

### ISSUE THREAD

**Issue by vext01** [Supervisor/supervisor#1233] opened 2019-04-30 10:19 UTC
Hi,

I had an autossh service in my config file (let's call it `mytun`), which I was unable to start:

```
[program:mytun]
autostart=false
command=/usr/local/bin/autossh -N -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -L ...
```

```
supervisor> start mytun
mytun: ERROR (no such file)
```

It took me a while to figure out what this was all about. The problem was, autossh wasn't installed! It would have been nice if it could have said something like:
```
mytun: ERROR 'autossh' (no such file)
```

**Comment by mnaberez** [comment] 2019-05-01 03:28
Duplicate of #103

**Closed by mnaberez** 2019-05-01 03:28 UTC
Labels: supervisorctl
