### ISSUE TITLE
[feature request] options to deal with bad logging situation

### ISSUE THREAD

**Issue by ElTopo** [Supervisor/supervisor#709] opened 2016-01-08 00:59 UTC
Hello,

Debian's supervisor package configures logfile path to be
/var/log/supervisor/supervisord.log
and creates /var/log/supervisor at installation.

However, when I put /var/log in tmpfs that directory may not exist after system reboot/reset, causing  supervisord exits with the following error:
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.

This is a bad situation since I depend on supervisord for running several other processes.

I would like to request some options to deal with this situation:
1. "create directory" option: when enabled, supervisord tries to create the directory (/var/log/supervisor) if it does not exist;
2. "continue on error" option: when enabled, if supervisord cannot write the log files (read-only filesystem, directory does not exist, etc.), it complains about the problem in daemon.log, but still continues to run without any loggings (samba works this way by default, if I don't have /var/log/samba directory, it disables all loggings but still keeps running). I much prefer my processes running with any logs to not running at all.

Thanks.

**Comment by mnaberez** [comment] 2016-01-08 01:05
Duplicate of #120 

> However, when I put /var/log in tmpfs that directory may not exist after system reboot/reset, causing supervisord exits with the following error:
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.

In your init script that launches `supervisord` at startup, put the command `mkdir /path/to/log` before the command `supervisord`.

**Closed by mnaberez** 2016-01-08 01:05 UTC
Labels: logging

**Comment by ElTopo** [comment] 2016-01-08 01:08
Thanks for the reply, I currently use a script to create the (hardcoded) directory but the problem is, the script does not know the logfile path (or rather, it has to parse supervisord.conf), it's easier and better that supervisord can handle this.

**Comment by tevino** [comment] 2016-03-15 07:49
As mentioned in #120, this feature will not deliver, what a shame. :worried: 

@ElTopo **syslog** and **systemd** are your friends.
