### ISSUE TITLE
allow supervisor to be behind a reverse proxy sub url (add base_url param)

### ISSUE THREAD

**Issue by feenes** [Supervisor/supervisor#1275] opened 2019-09-05 23:25 UTC
Hi,

In some cases I'd like to put supervisor behind one (or a chain of reverse proxies and be able to access it via a sub url)

Example:
I'd like the supervisor web interface to be acessible via
https://myserver.mydomain.com/supervisor/

Under some circumstances (using haproxy as a tcp proxy with sni detection, forwarding to nginx ssl terminal with the haproxy proxy protocol and then pointing to the http_inetserver redirects / links within the supervisor web interface are wrong (bad port number or bad url without the desired /supervisor/ prefix.

havin ab optional  base_url parameter in the [inet_http_server] could solve this issue.

In my example the parameter would be set to
base_url = https://myserver.mydomain.com/supervisor/

and the whole web interface would prefix it's links with the base url.

Alternatively. 
Perhaps there are already tricks to configure a haproxy / nginx setup such, that this feature is not necessary.

In this case a documentation of how to configure nginx could be helpful:

On some servers following nginx setup seems to do the trick:

```
   location ^~ /supervisor/ {
        rewrite ^/supervisor(/.*) $1 break;
        proxy_pass http://localhost:9001/;
        proxy_set_header Host $host/supervisor/;  # I'm not even sure this is really legal but it seems to do
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
   }
```

But on more complex setups I'd really need some advice of how to achieve this and I think the base_url param would be a simple way. (such an approach is done by quite some web apps)

Example which I did not get to work:

Desired url, that should allow me to connect to supervisor
https://myserver.mydomain.com/supervisor/

this will arrive at an haproxy in tcp mode, which will redirect to an nginx via
https://internalhostname:444/supervisor (with the haproxy protocol)
and this one would have an nginx configuration like the above example:

However the generated urls do contain the port 444 and will be translated to
https://myserver.mydomain.com:444/supervisor/

Thus the setup is broken.

**Comment by mnaberez** [comment] 2019-09-05 23:46
Duplicate of #29

**Closed by mnaberez** 2019-09-05 23:46 UTC
Labels: web
