### ISSUE TITLE
How to make sure restart a process with or without new config by automation script?

### ISSUE THREAD

**Issue by cupen** [Supervisor/supervisor#1239] opened 2019-05-05 03:37 UTC
Hello.
I am writing automation script for add/restart/remove some processes. 
I can use `reread`,  `update or restart process` for this case manually, but how could I do it by automation script?

describe my case by pseudo-code.
```python
supervisorctl sign QUIT process
sleep 30
if config is changed):
    supervisorctl update process
else:
    supervisorctl restart process
```
Is there a easy way for this?

**Comment by cupen** [comment] 2019-05-07 10:48
Hello.
I meet the same problem as #910,  My stateful-program can't restart twice.
Maybe add a command `supervisorctl restart program --update` would be better?

**Comment by cupen** [comment] 2019-05-09 07:44
or this?
```bash
supervisorctl remove program
supervisorctl add program
```

**Comment by mnaberez** [comment] 2019-05-24 15:58
> this question is the same as #910.

Closing as a duplicate of #910.

**Closed by mnaberez** 2019-05-24 15:58 UTC
Labels: question

**Comment by cupen** [comment] 2019-05-25 03:20
don't close it plz. your advice for #910 is  … using eventlistener. it's doable but make it so harder than it needs to be.
I just want to restart a program by automation script.
pseudo-code:
    
    if program.config is changed:
        supervisorctl update program
    else:
        supervisorctl restart program

but how to know config is changed or not?

it’s no problem if no answer now. maybe we 
 have a good answer in the future.
so, reopen this issue plz.

**Comment by cupen** [comment] 2019-05-30 08:37
@mnaberez  Hello, please reopen this issue. this is a real problem. 
@nilstoedtmann I found a ugly solution, but this is not good enough.

```bash
supervisorctl stop program
supervisorctl remove program
supervisorctl update program
```
my boss ask me:"why do'nt you just restart it?" 
:worried: “en... because ……”
