### ISSUE TITLE
View "unified" log during development

### ISSUE THREAD

**Issue by andyfry01** [Supervisor/supervisor#1416] opened 2021-03-04 15:00 UTC
Hello, firstly, this is a wonderful library! I find most CLI tools pretty alienating to work with, but Supervisor is really nice to work with. 

One thing I want to do is view all of the logs coming out of an app in one unified stream. Something like `tail -f all-logs`. Is that possible to do? Or are all logs split up by log level and type no matter what?

This would be useful specifically during development. Sometimes I'll make a change to a running app, and it will produce an error or a compilation step won't execute successfully, and I won't see it from the logs I get from `tail -f <appname>`. 

If I were to run that same app directly in the terminal as a foreground process, I would see that kind of thing straight away though. 

Anyway, thank you 🙇‍♂️

**Comment by mnaberez** [comment] 2021-03-04 16:34
Duplicate of #246

**Closed by mnaberez** 2021-03-04 16:34 UTC
Labels: supervisorctl
