### ISSUE TITLE
Add all config variables to api getProcessInfo results

### ISSUE THREAD

**Issue by mikeyg123** [Supervisor/supervisor#791] opened 2016-07-19 15:58 UTC
Please extend the struct returned by the getProcessInfo api call to include the values of all the variables set in the [program:x] section of the config for each process.

Also please allow other arbitrary variables to be set in this config section, substituted into the command and returned in the same structure.

We have several hundred processes under supervisor with a home-grown UI. This has become the central point for many support functions but could be improved if more information was available.  In particular  being able to retrieve and display the command, directory and environment variables would really help in support situations.  Considering that it's probably a very small change it would be sensible to include all program section variables.

Even better - if arbitrary variables could be set in the config and substituted into the launch command as well as being made available via the api then the UI could do much more including: group processes by environment or department, link directly to hosted websites, or custom control panel, launch clients and diagnostic tools for the specific process instances etc. All while keeping the config declarative and in a single place.

**Comment by mnaberez** [comment] 2016-07-19 21:31
> Please extend the struct returned by the getProcessInfo api call to include the values of all the variables set in the [program:x] section of the config for each process.

Duplicate of #670.

> Also please allow other arbitrary variables to be set in this config section, substituted into the command and returned in the same structure.

Duplicate of #330.

**Closed by mnaberez** 2016-07-19 21:31 UTC
