### ISSUE TITLE
How can i graceful restart a program ?

### ISSUE THREAD

**Issue by sdbaiguanghe** [Supervisor/supervisor#624] opened 2015-06-13 09:32 UTC
i have a program that need zero-downtime  restarts  which mean without dropping any connections.
when this program receive  signal USR1,it will fork&exec a child process handle the new conntion and when the parent finish all the previous conntion it will exit.i want supervisor  supervisor the child process. 
what should i do to achieve my purpose? how supervisor restart a program ,send a TERM signal to stop and then start? 
my english is poor , i hope you can understand what i mean,thanks ..

**Comment by mnaberez** [comment] 2015-06-13 16:33
Duplicate of #53.

**Closed by mnaberez** 2015-06-13 16:33 UTC
