### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by kiranchari** [Supervisor/supervisor#727] opened 2016-02-26 07:41 UTC
I am using python virtualenv and I have installed the latest setuptools in my virtualenv (as well as in the system python) (I've deleted distribute and any old version of setuptools from site-packages)

supervisorctl is still unable find pkg_resources. How do I tell supervisorctl which python binary to use? Or would anything else work?

`Traceback (most recent call last):
  File "/usr/local/bin/supervisorctl", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
`

**Comment by mnaberez** [comment] 2016-02-29 19:05
> supervisorctl is still unable find pkg_resources. 

Supervisor imports `pkg_resources` [like any other package](https://github.com/Supervisor/supervisor/blob/3.2.1/supervisor/options.py#L15).  `pkg_resources` is provided by [setuptools](https://pypi.python.org/pypi/setuptools), so Supervisor should be able to import it if setuptools is installed correctly in its environment.

> How do I tell supervisorctl which python binary to use? 

There's no way to tell Supervisor to use a certain Python environment.  Instead, you install Supervisor into the Python environment you want to use, and it uses the packages in that environment.

> Or would anything else work?

This problem seems to be caused by a broken Python environment rather than something specific to Supervisor.  There's not anything more we can do here, so I am going to close this issue.

**Closed by mnaberez** 2016-02-29 19:05 UTC
Labels: packaging

**Comment by CharlieReitzel** [comment] 2021-09-27 22:56
I'm seeing this exact issue trying to run with Python 3.9 in a Photon based container.  What am I doing wrong?

```
RUN tdnf install -y postgresql openjre8 python3 python3-pip
...
RUN pip3 install supervisor
```

Inside the container:
```
$ /usr/bin/supervisord --help
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from supervisor.supervisord import main
  File "/usr/lib/python3.9/site-packages/supervisor/supervisord.py", line 41, in <module>
    from supervisor.options import ServerOptions
  File "/usr/lib/python3.9/site-packages/supervisor/options.py", line 13, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
