### ISSUE TITLE
Add prefix to supervisord program stdout logs

### ISSUE THREAD

**Issue by sffc** [Supervisor/supervisor#1326] opened 2020-02-08 20:58 UTC
I'm using supervisord in Docker and have my application logs configured like so:

```
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
```

In the stdout of supervisord, though, the messages get displayed directly from the subprocesses, and it is not always possible to tell which subprocess is responsible for which log message.  For example, I see something like this:

```
2020-02-08 20:49:27,572 INFO supervisord started with pid 1
2020-02-08 20:49:28,583 INFO spawned: 'nginx' with pid 8
2020-02-08 20:49:28,585 INFO spawned: 'php-fpm' with pid 9
[08-Feb-2020 20:49:28] NOTICE: fpm is running, pid 9
[08-Feb-2020 20:49:28] NOTICE: ready to handle connections
[08-Feb-2020 20:49:28] NOTICE: systemd monitor interval set to 10000ms
```

The first 3 messages are from supervisord itself, and the last 3 are from php-fpm.  I would rather see something like this:

```
2020-02-08 20:49:27,572 INFO supervisord started with pid 1
2020-02-08 20:49:28,583 INFO spawned: 'nginx' with pid 8
2020-02-08 20:49:28,585 INFO spawned: 'php-fpm' with pid 9
2020-02-08 20:49:28,600 INFO program php-fpm: NOTICE: fpm is running, pid 9
2020-02-08 20:49:28,601 INFO program php-fpm: NOTICE: ready to handle connections
2020-02-08 20:49:28,602 INFO program php-fpm: NOTICE: systemd monitor interval set to 10000ms
```

Then, if I'm interested only in the logs from php-fpm, I can easily grep for them.

**Comment by mnaberez** [comment] 2020-02-08 21:02
Duplicate of #553

**Closed by mnaberez** 2020-02-08 21:02 UTC
Labels: logging
