### ISSUE TITLE
 supervisorctl merge stdout+stderr to save time

### ISSUE THREAD

**Issue by mrx23dot** [Supervisor/supervisor#1615] opened 2023-12-15 21:57 UTC
A new parameter would be nice like that prints stdout (possibly longer) first, then stderr (more important) last.

`supervisorctl tail xxx both`

instead of two steps
```
supervisorctl tail xxx stdout
supervisorctl tail xxx stderr
```
Unless there is a way to capture the original intverleaved one

Would save a few seconds everytime we need to investigate.

-tail will be a bit trickier.

A nother small idea, .rstrip() the output when printing to console,
since default output is only a few lines long we don't want to waste it on trailing new lines.

**Comment by mnaberez** [comment] 2023-12-19 16:40
Duplicate of #246 (Title is "multiple processes" but comments request merged `stdout`/`stderr`)

**Closed by mnaberez** 2023-12-19 16:40 UTC
