### ISSUE TITLE
'xml.parsers.expat.ExpatError' when using tail

### ISSUE THREAD

**Issue by WhyNotHugo** [Supervisor/supervisor#531] opened 2014-12-04 17:03 UTC
An exception is thrown ocasionally when tailing:

```
$ supervisorctl -c $HOME/.config/supervisor/supervisord.conf tail offlineimap
error: <class 'xml.parsers.expat.ExpatError'>, not well-formed (invalid token): line 9, column 55: file: /usr/lib/python2.7/xmlrp
clib.py line: 557
```

I've found _no pattern_ for this so far.
The [configuration file](/hobarrera/dotfiles/blob/master/home/.config/supervisor/supervisord.conf) and [service](/hobarrera/dotfiles/blob/master/home/.config/supervisor/services/offlineimap) file are pretty straightforward.

**Comment by nwgat** [comment] 2015-04-02 04:11
i also get this, its realy annoying
it seems to be related to rtorrent tail log, it does not happend on a nodejs tail logs

**Comment by pesterhazy** [comment] 2015-09-22 13:56
I'm also seeing the same problem when I try to tail a process's `stderr` channel.

**Comment by pesterhazy** [comment] 2015-09-22 14:01
I suspect this occurs when there's **bold** print (ANSI codes).

**Comment by hobarrera** [comment] 2015-09-22 17:50
Indeed, it's generaly ansi codes. Adding `strip_ansi=True` to the `[supervisord]` section of your config should avoid this repeating. IMHO, it should be the default.

**Comment by pesterhazy** [comment] 2015-09-23 12:36
That's useful, @hobarrera, thanks! It's still a bug that you need this option for `tail` to work with Ansi codes (npm being a common example).

**Comment by hobarrera** [comment] 2015-09-26 06:27
Oh, yes, I agree that it's a bug. The default should `strip_ansi` by default until the underlying xml library has been fixed to deal with it properly. I was merely pointing out a quick workaround for other that land here in the meantime. :)

**Comment by arnuschky** [comment] 2015-09-30 17:08
@pesterhazy, did `strip_ansi` work for you? Doesn't have any effect for me somehow (tail still breaks). Running 3.1.3

**Comment by hobarrera** [comment] 2015-09-30 18:07
`strip_ansi` changes how the new logs are saved, so existing logs will still fail, but new logs will be saved without the offending characters.

If possible, truncate (or just move) any old logs, then restart.

**Comment by arnuschky** [comment] 2015-10-01 09:12
Hmm, didn't help, but it seems I was following a red herring: it's the logging that breaks for me (i.e., the logfile stops) rather than the tail command. I thought stopping is caused by the ANSI codes. If it would be only tail, then the log file should be complete and I should see ANSI codes in the log file, right?

**Comment by pesterhazy** [comment] 2015-10-01 10:11
@arnuschky, yes only `tail` is affected by this bug. The workaround of using `strip_ansi` works for me.

Agree with @hobarrera, it may be necessary to remove old logs which may still include ANSI codes.

**Comment by vijayviji** [comment] 2015-10-17 17:05
`strip_ansi` is not working for me. Here's the supervisor config file -> http://pastebin.com/QFzpg5Jg

I'm using ubuntu 14.04 in VM. The app folder is shared b/w host and the VM. Host is Windows 10.

**Comment by mnaberez** [comment] 2018-02-23 05:23
Duplicate of #85

**Closed by mnaberez** 2018-02-23 05:23 UTC
Labels: supervisorctl, xmlrpc
