### ISSUE TITLE
How can I run update without starting services that are currently not started?

### ISSUE THREAD

**Issue by 884756834** [Supervisor/supervisor#1161] opened 2018-10-16 18:54 UTC
From the docs:
> reread
> Reload the daemon’s configuration files, without add/remove (no restarts)
> update
> Reload config and then add and remove as necessary (restarts programs)

What I want to actually do is reload the config files, with the add/remove, but without starting any services that are currently not started.

Use case: Installation script which turns off services, does the upgrade, wants to ensure supervisorctl is up to date but without actually starting the services as they need to be manually started the first time.

**Comment by mnaberez** [comment] 2018-10-16 19:00
Duplicate of #214

**Closed by mnaberez** 2018-10-16 19:00 UTC
