### ISSUE TITLE
supervisorctl can not used

### ISSUE THREAD

**Issue by xyjwsj** [Supervisor/supervisor#1247] opened 2019-06-04 03:27 UTC
In Macos 10.14.5, supervisorctl can not used.
Error: .ini file does not include supervisorctl section.
In my supervisor.ini, I already config supervisord and supervisorctl.

How to use it?

**Comment by mnaberez** [comment] 2019-06-04 21:03
> In Macos 10.14.5, supervisorctl can not used.
> Error: .ini file does not include supervisorctl section.
> In my supervisor.ini, I already config supervisord and supervisorctl.

Here's what I tried to reproduce this.

Run `supervisord` in the foreground:

```text
$ system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: macOS 10.14.5 (18F132)

$ supervisord --version 
4.0.3 

$ cat supervisord.conf
[supervisord]

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat
startsecs = 0
autorestart = false

$ supervisord -n -c ./supervisord.conf
2019-06-04 13:56:19,531 INFO Increased RLIMIT_NOFILE limit to 1024
2019-06-04 13:56:19,549 INFO RPC interface 'supervisor' initialized
2019-06-04 13:56:19,549 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2019-06-04 13:56:19,549 INFO supervisord started with pid 3945
2019-06-04 13:56:20,555 INFO spawned: 'cat' with pid 3948
2019-06-04 13:56:21,559 INFO success: cat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
```

In another terminal, run `supervisorctl`:

```
$ supervisorctl -c ./supervisord.conf status
cat                              RUNNING   pid 3948, uptime 0:00:40

$ supervisorctl -c ./supervisord.conf stop cat
cat: stopped
```

As can be seen above, `supervisorctl` does work on macOS 10.14.5.  Since I am unable to duplicate this, I am going to close this issue.  My guess is that either the contents of the configuration file are wrong, or that `supervisord` or `supervisorctl` are not using the configuration file you think they are (try explicit `-c`).  Please see [Configuration](http://supervisord.org/configuration.html) for more.

**Closed by mnaberez** 2019-06-04 21:03 UTC
Labels: question, supervisorctl
