### ISSUE TITLE
colored logfile out (strip_ansi) change?

### ISSUE THREAD

**Issue by proximous** [Supervisor/supervisor#860] opened 2016-12-06 23:28 UTC
My output uses control characters for colored output. With supervisord 3.0 (Ubuntu 15.10) my logfiles have the control codes and I get colored output.  With supervisord 3.2.0 (Ubuntu 16.04) my logfiles no longer have the control codes so no color.  In both cases, I don't have strip_ansi in my config.  Did the default behavior change between these versions?  I tried adding 'strip_ansi=false' to my config but did not get the colors back.

**Comment by mnaberez** [comment] 2016-12-07 15:57
> With supervisord 3.2.0 (Ubuntu 16.04) my logfiles no longer have the control codes so no color. In both cases, I don't have strip_ansi in my config. Did the default behavior change between these versions?

No, the default value for the `strip_ansi` option in the [`[supervisord]`](http://supervisord.org/configuration.html#supervisord-section-settings) section is `false` in Supervisor 3.2.0 (and all versions at this time).  Here's what I tried to reproduce your report:

```
$ cat supervisord.conf
[supervisord]
logfile = /tmp/supervisord.log
;Note: there is no strip_ansi= here, so the default of false will be used.

[program:printf]
command = printf '\e[0;31mhello'
startsecs = 0
autorestart = false
stdout_logfile = /tmp/printf.log

$ supervisord --version
3.2.0

$ supervisord -n -c supervisord.conf 
2016-12-07 07:49:37,570 INFO supervisord started with pid 75003
2016-12-07 07:49:38,573 INFO spawned: 'printf' with pid 75007
2016-12-07 07:49:38,579 INFO success: printf entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-12-07 07:49:38,579 INFO exited: printf (exit status 0; expected)
^C2016-12-07 07:49:40,362 WARN received SIGINT indicating exit request

$ od -t x1 -c /tmp/printf.log 
0000000  1b  5b  30  3b  33  31  6d  68  65  6c  6c  6f
        033   [   0   ;   3   1   m   h   e   l   l   o
```

As shown above, there is no `strip_ansi=` option in the config file, and `supervisord` did not strip the escape sequence when writing the log file.

I'm going to close this issue since I can't reproduce it.  If you can provide reproduce instructions that show `supervisord` incorrectly stripping escape sequences, we can reopen.

**Closed by mnaberez** 2016-12-07 15:57 UTC
Labels: logging

**Comment by proximous** [comment] 2016-12-07 18:10
Thanks for the quick reply and taking the time to provide a test case. I appreciate it.
I can confirm your test case works for me also, so clearly the issue is with my configuration.
I've tried to debug but still can't find the issue. When I run my program from the command line I get colors, so maybe I'm getting outsmarted with some interactive/non-interactive shell detection. When I figure it out I'll post it here to help others.

Thanks again!

**Comment by proximous** [comment] 2017-01-31 05:02
FYI, my issue turned out to be [colorlog](https://github.com/borntyping/python-colorlog) which uses [colorama](https://github.com/tartley/colorama) (when present) which strips ANSI when output is not a tty.
