### ISSUE TITLE
"Too many processes in process table to spawn" in python 3 but ok in python 2

### ISSUE THREAD

**Issue by rabbit8ge** [Supervisor/supervisor#1521] opened 2022-07-02 07:34 UTC
I started almost 1k programs in supervisor 4.2.4 with anaconda3 python. some programs failed to start with error "Too many processes in process table to spawn". While the same programs run well in supervisor 4.0.3 with python 2.7.
I don't know what's the difference between the two version python.

**Comment by mnaberez** [comment] 2022-07-12 18:10
Here's what I tried to reproduce this.  I created a config file with 2 programs, 5 processes each, for a total of 10 processes:

```text
$ cat supervisord.conf
[supervisord]
nodaemon = true

[program:cat1]
command = /bin/cat
process_name = %(program_name)s_%(process_num)d
numprocs = 5
startsecs = 0
autorestart = false

[program:cat2]
command = /bin/cat
process_name = %(program_name)s_%(process_num)d
numprocs = 5
startsecs = 0
autorestart = false

$ supervisord --version
4.2.4

$ supervisord -c supervisord.conf 
2022-07-12 10:29:43,947 INFO supervisord started with pid 92954
2022-07-12 10:29:44,952 INFO spawned: 'cat1_0' with pid 92955
2022-07-12 10:29:44,955 INFO spawned: 'cat1_1' with pid 92956
2022-07-12 10:29:44,957 INFO spawned: 'cat1_2' with pid 92957
2022-07-12 10:29:44,960 INFO spawned: 'cat1_3' with pid 92958
2022-07-12 10:29:44,963 INFO spawned: 'cat1_4' with pid 92959
2022-07-12 10:29:44,965 INFO spawned: 'cat2_0' with pid 92960
2022-07-12 10:29:44,968 INFO spawned: 'cat2_1' with pid 92961
2022-07-12 10:29:44,970 INFO spawned: 'cat2_2' with pid 92962
2022-07-12 10:29:44,972 INFO spawned: 'cat2_3' with pid 92963
2022-07-12 10:29:44,974 INFO spawned: 'cat2_4' with pid 92964
2022-07-12 10:29:45,981 INFO success: cat1_0 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,981 INFO success: cat1_1 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,981 INFO success: cat1_2 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,981 INFO success: cat1_3 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,981 INFO success: cat1_4 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,982 INFO success: cat2_0 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,982 INFO success: cat2_1 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,982 INFO success: cat2_2 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,982 INFO success: cat2_3 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-07-12 10:29:45,982 INFO success: cat2_4 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
``` 

I ran this on both Python 2.7.16 and Python 3.9.13.  In both cases, it showed that exactly 10 processes were spawned.
I also used `pstree` to verify it.  

>  some programs failed to start with error "Too many processes in process table to spawn". 

The error is emitted here:

https://github.com/Supervisor/supervisor/blob/e3601a87f0b6c52b97e41dc7dbc4aaffaf0ae175/supervisor/process.py#L240-L247

[`options.fork()`](https://github.com/Supervisor/supervisor/blob/e3601a87f0b6c52b97e41dc7dbc4aaffaf0ae175/supervisor/options.py#L1524-L1525) is just `os.fork()`.  It's the same code on both Python 2 and 3.  

> I started almost 1k programs in supervisor 4.2.4 with anaconda3 python

That is a large number of processes.  My guess is that the process table really was full for some reason unrelated to Supervisor, e.g. perhaps the computer happened to have a few more processes running at the time you tested on Python 3 than when you tested on Python 2.  I'm going to close this issue because I can't see any difference in the number of processes spawned when run on Python 2 vs. Python 3.

**Closed by mnaberez** 2022-07-12 18:10 UTC
Labels: python 3
