### ISSUE TITLE
reread does not find changes to event listeners

### ISSUE THREAD

**Issue by mikeyg123** [Supervisor/supervisor#806] opened 2016-08-03 11:10 UTC
Change event listener command in the config file
call reread 
it finds no changes

Thoughts: maybe this is because reread returns groups that have changes and event listeners don't really fit into groups? - at least you can't specify a group for them that we have found.

**Comment by mnaberez** [comment] 2016-08-03 14:15
Duplicate of #339.

**Closed by mnaberez** 2016-08-03 14:15 UTC
Labels: events
