### ISSUE TITLE
no reponse when started more than 1k programs

### ISSUE THREAD

**Issue by rabbit8ge** [Supervisor/supervisor#1511] opened 2022-05-28 02:15 UTC
no reponse when i execute supervisorctl status

**Comment by mnaberez** [comment] 2022-08-17 00:37
Here's what I tried to reproduce this.  I started `supervisord` with 1001 subprocesses of `/bin/cat`:

```text
$ supervisord --version
4.2.4

$ cat supervisord.conf
[supervisord]
minfds=8192
nodaemon=true

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat
process_name = %(program_name)s_%(process_num)04d 
numprocs = 1001
startsecs = 0
autorestart = false

$ supervisord -c supervisord.conf 
2022-08-16 17:11:17,355 INFO Increased RLIMIT_NOFILE limit to 8192
2022-08-16 17:11:17,671 INFO RPC interface 'supervisor' initialized
2022-08-16 17:11:17,671 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2022-08-16 17:11:17,671 INFO supervisord started with pid 66732
2022-08-16 17:11:18,677 INFO spawned: 'cat_0000' with pid 66733
2022-08-16 17:11:18,679 INFO spawned: 'cat_0001' with pid 66734
2022-08-16 17:11:18,682 INFO spawned: 'cat_0002' with pid 66735
2022-08-16 17:11:18,686 INFO spawned: 'cat_0003' with pid 66736
2022-08-16 17:11:18,689 INFO spawned: 'cat_0004' with pid 66737
...
2022-08-16 17:11:24,617 INFO success: cat_0996 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-08-16 17:11:24,617 INFO success: cat_0997 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-08-16 17:11:24,617 INFO success: cat_0998 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-08-16 17:11:24,617 INFO success: cat_0999 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-08-16 17:11:24,617 INFO success: cat_1000 entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
```

In another terminal:
```text 
$ supervisorctl -c supervisord.conf status
cat:cat_0000                     RUNNING   pid 66733, uptime 0:01:30
cat:cat_0001                     RUNNING   pid 66734, uptime 0:01:30
cat:cat_0002                     RUNNING   pid 66735, uptime 0:01:30
cat:cat_0003                     RUNNING   pid 66736, uptime 0:01:30
cat:cat_0004                     RUNNING   pid 66737, uptime 0:01:30
...
cat:cat_0996                     RUNNING   pid 67730, uptime 0:01:25
cat:cat_0997                     RUNNING   pid 67731, uptime 0:01:25
cat:cat_0998                     RUNNING   pid 67732, uptime 0:01:25
cat:cat_0999                     RUNNING   pid 67733, uptime 0:01:25
cat:cat_1000                     RUNNING   pid 67734, uptime 0:01:25

$ supervisorctl -c supervisord.conf status | grep RUNNING | wc -l
    1001
```

Since there doesn't seem to be a hard limit of 1000 subprocesses, I am going to close this issue.  If the subprocesses you are running are outputting on their `stdout` and `stderr` file descriptors, `supervisord` has to spend more time logging.  This additional load might be too much.  I don't think there's anything we can do about that, other than to suggest running fewer subprocesses.

**Closed by mnaberez** 2022-08-17 00:37 UTC
