### ISSUE TITLE
The supervisor daemon node process restarts the service after no access for a long time

### ISSUE THREAD

**Issue by 529082819** [Supervisor/supervisor#1302] opened 2019-12-06 04:43 UTC

**Comment by 529082819** [comment] 2019-12-06 04:45
Service will restart after 24 hours without access

**Comment by mnaberez** [comment] 2019-12-14 20:55
Here's some output a `supervisord` instance I am running:

```
$ supervisorctl status
memmon     RUNNING   pid 6641, uptime 86 days, 14:17:28
...

$ supervisord --version 
4.0.3
```

The `uptime` above shows the process has been running for over 86 days without restart.  

There is no "restart a subprocess after a time period" option in either `supervisord` or `supervisorctl`.  There is probably some other reason your subprocesses are restarting, e.g. maybe something else on the system is sending a restart signal to `supervisord`.  Look in the main `supervisord.log` file for clues.

I am going to close this issue because I don't believe it is an issue in Supervisor.  If you can provide reproduce instructions that show it is an issue in Supervisor, we can reopen.

**Closed by mnaberez** 2019-12-14 20:55 UTC
