### ISSUE TITLE
Delay between process starts or restarts?

### ISSUE THREAD

**Issue by aib** [Supervisor/supervisor#1189] opened 2018-12-28 13:46 UTC
My processes are failing immediately after startup.

Supervisor is trying to restart them indefinitely, which is good, but it's doing this at the fastest pace it can, which is bad. My CPU usage is 100% and my supervisor logs are flooded.

Is there any way to add a delay before starting or restarting a program?

**Comment by mnaberez** [comment] 2018-12-28 17:19
Duplicate of #487
Duplicate of #323

**Closed by mnaberez** 2018-12-28 17:19 UTC
