### ISSUE TITLE
Support for nested groups?

### ISSUE THREAD

**Issue by nickolai-voyage** [Supervisor/supervisor#1303] opened 2019-12-06 22:56 UTC
It seems that a `[group:x]` can only launch programs, could it be upgraded to control nested groups? This would be really handy to be able to collect related groups into a larger group, i.e.

```
[group:sensors]
programs=lidar,gps

[group:algorithms]
programs=sensor_fusion,mapping

[group:main]
groups=sensors,algorithms
```

Right now, main would have to list all 4 programs, since groups cannot be listed. What sort of effort might be involved in adding a feature like this? We could be open to paying for the work.

**Comment by mnaberez** [comment] 2019-12-07 01:21
Duplicate of #1250

**Closed by mnaberez** 2019-12-07 01:21 UTC

**Comment by nickolai-voyage** [comment] 2019-12-08 21:43
Thanks for linking to the duplicate issue, but I see it doesn't have any update. Is this something that may be supported in a future release? What sort of scope would there be to this feature?

**Comment by YontiLevin** [comment] 2023-04-07 09:39
any news on this feature request?
