### ISSUE TITLE
add current date to log's filename

### ISSUE THREAD

**Issue by khanzadimahdi** [Supervisor/supervisor#1351] opened 2020-05-30 06:28 UTC
I want to store logs of each day in different log files.

for example:
- supervisor-2020-05-20.log
- supervisor-2020-05-21.log
- supervisor-2020-05-22.log
- supervisor-2020-05-23.log

how can I do that in my config file? my current config file is like the below:

```
stdout_logfile = supervisor.log
```

**Comment by mnaberez** [comment] 2020-05-30 06:36
Duplicate of #1265

**Closed by mnaberez** 2020-05-30 06:36 UTC
Labels: logging
