### ISSUE TITLE
ExpatError: not well-formed for NULs in supervisor.log pulled by readLog API

### ISSUE THREAD

**Issue by jem-ka** [Supervisor/supervisor#744] opened 2016-04-21 21:43 UTC
Somehow (power pull? not sure) my supervisord log ended up with a sequence of NUL characters in it. When I use the xmlrpc API to read the log it throws an exception because the NUL characters are not XML escaped.

minimal test python:

```
from supervisor.xmlrpc import SupervisorTransport
from xmlrpclib import ServerProxy
transport = SupervisorTransport(None, None, serverurl="unix:///var/run/supervisor.sock")
proxy = ServerProxy('http://127.0.0.1', transport=transport)
supervisor_log_lines = proxy.supervisor.readLog(-512 * 1024, 0)
```

Debug session:

```
$ python -d -i test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    supervisor_log_lines = proxy.supervisor.readLog(-512 * 1024, 0)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
  File "/usr/lib/python2.7/site-packages/supervisor/xmlrpc.py", line 474, in request
  File "/usr/lib/python2.7/xmlrpclib.py", line 558, in feed
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1033, column 0
>>> import pdb
>>> pdb.pm()
> /usr/lib/python2.7/xmlrpclib.py(558)feed()
(Pdb) data.split('\n')[1032]
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002016-01-01 00:00:22,190 CRIT Supervisor running as root (no user in config file)'
(Pdb) data.split('\n')[1031]
'2016-01-01 00:00:28,159 INFO success: node entered RUNNING state, process has stayed up for &gt; than 1 seconds (startsecs)'
```

```
$ supervisord --version
3.0a12
```

**Comment by mnaberez** [comment] 2016-12-26 23:19
Duplicate of #85 or #531.

**Closed by mnaberez** 2016-12-26 23:19 UTC
Labels: logging, xmlrpc
