### ISSUE TITLE
Supervisor fails on start with "ImportError: No module named process"

### ISSUE THREAD

**Issue by rordi** [Supervisor/supervisor#972] opened 2017-08-03 12:10 UTC
Supervisor fails on start with "ImportError: No module named process"

Supervisor version 3.3.3 installed with easy_install
OS: Debian 8.7

```
Thu Aug  3 14:28:08 CEST 2017: Starting /usr/local/bin/supervisord -c /etc/supervisor/conf.d/iwfsupervisor.conf ...
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 9, in <module>
  File "/usr/local/lib/python2.7/dist-packages/supervisor-3.3.3-py2.7.egg/supervisor/supervisord.py", line 363, in main
  File "/usr/local/lib/python2.7/dist-packages/supervisor-3.3.3-py2.7.egg/supervisor/supervisord.py", line 373, in go
  File "/usr/local/lib/python2.7/dist-packages/supervisor-3.3.3-py2.7.egg/supervisor/supervisord.py", line 84, in main
  File "/usr/local/lib/python2.7/dist-packages/supervisor-3.3.3-py2.7.egg/supervisor/supervisord.py", line 92, in run
  File "/usr/local/lib/python2.7/dist-packages/supervisor-3.3.3-py2.7.egg/supervisor/supervisord.py", line 125, in add_process_group
  File "/usr/local/lib/python2.7/dist-packages/supervisor-3.3.3-py2.7.egg/supervisor/options.py", line 1875, in make_group
ImportError: No module named process
```

**Comment by mnaberez** [comment] 2017-08-04 17:29
> Supervisor fails on start with "ImportError: No module named process"

Here's what I tried to reproduce this.

Install `supervisor` in an environment where it has never been installed:

```
$ pip install supervisor
Collecting supervisor
  Downloading supervisor-3.3.3.tar.gz (418kB)
    100% |████████████████████████████████| 419kB 1.5MB/s 
Collecting meld3>=0.6.5 (from supervisor)
  Downloading meld3-1.0.2-py2.py3-none-any.whl
Installing collected packages: meld3, supervisor
  Running setup.py install for supervisor ... done
Successfully installed meld3-1.0.2 supervisor-3.3.3
```

Check version installed:
```
$ supervisord --version
3.3.3
```

Try the [import that fails](https://github.com/Supervisor/supervisor/blob/3.3.3/supervisor/options.py#L1875) in your report above:
```
$ python2
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from supervisor.process import ProcessGroup
>>>
```


Minimal `supervisord.conf`:
```
$ cat supervisord.conf
[supervisord]
logfile = /tmp/supervisord.log

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat
```

Start `supervisord` in the foreground with that config:
```
$ supervisord -n -c supervisord.conf 
2017-08-04 10:16:58,716 INFO RPC interface 'supervisor' initialized
2017-08-04 10:16:58,716 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2017-08-04 10:16:58,716 INFO supervisord started with pid 3001
2017-08-04 10:16:59,720 INFO spawned: 'cat' with pid 3004
2017-08-04 10:17:00,723 INFO success: cat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

I don't know the cause of your error but the package seems fine.  You seem to have a broken installation somehow, but I don't know why or how to fix it.

In the comments that you deleted, you wrote:

> Supervisor 3.3.3 on Debian GNU/Linux 8.7
> apt-get remove -y supervisor python-meld3 && \
apt-get install -y sudo python-pip && \
pip install --upgrade supervisor`

It looks like may have been running the Debian packaged version at one point and then switched to the Python package.  That may have something to do with it.  I don't know.

I can't find anything wrong with the Python package so I am going to close this issue.

**Closed by mnaberez** 2017-08-04 17:29 UTC

**Comment by et304383** [comment] 2017-10-18 11:22
Encountering the same issue on Amazon Linux using the version available from yum through epel 6.  I guess the yum version is abandoned?

**Comment by aviksama** [comment] 2018-02-03 09:50
Check if you have installed supervisor in your virtual environment. Which can cause the import issue.

**Comment by KeithTt** [comment] 2023-08-21 02:48
Maybe you install supervisord by yum, and the default python version is python2.6.

You may need to change the shabang of supervisorctl command file `/usr/bin/supervisorctl` from `#!/usr/bin/python` to `#!/usr/bin/python2.6`.
