### ISSUE TITLE
Tail -f option in the web interface doesnt work.

### ISSUE THREAD

**Issue by ghost** [Supervisor/supervisor#149] opened 2012-09-08 16:18 UTC
On the web page to control the processes, the Tail -f link doesn't work (the server doesn't respond anything, so the browser doesn't show anything). The href attribute of the link is
http://localhost:8080/logtail/recommender_server%3Arecommender_server_01
where recommender_server is the process name. 

Nevertheless the Clear Log link works well. In this case, the href attribute of the link is:
http://localhost:8080/index.html?processname=recommender_server%3Arecommender_server_01&action=clearlog

My operating systems is: OS X Mountain Lion (Mac Book Pro)

; MY CONFIGURATION FILE FOR SUPERVISORD

[unix_http_server]
file=/Users/rmerinogarcia/Proyects/temp/supervisor.sock  
username=user  
password=123     

[inet_http_server]  
port=127.0.0.1:8080  
username=user  
password=123              

[supervisord]
logfile=/Users/rmerinogarcia/Proyects/temp/supervisord.log 
logfile_maxbytes=50MB  
logfile_backups=10  
loglevel=info  
pidfile=/Users/rmerinogarcia/Proyects/temp/supervisord.pid 

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:recommender_server]
process_name=%(program_name)s_%(process_num)02d
numprocs=1
numprocs_start=1
command=/Users/rmerinogarcia/.Envs_Python_2.7.3/USG_ENGINE/bin/python /Users/rmerinogarcia/.Envs_Python_2.7.3/USG_ENGINE/bin/start_recommender.py -p 91%(process_num)02d
stdout_logfile=/Users/rmerinogarcia/Proyects/temp/recommender.out
redirect_stderr=true
autorestart=true

**Comment by Shellbye** [comment] 2015-01-29 09:12
I have the same issue but fixed by add childlogdir = %(here)s to [supervisord]. And all my [program] have the directory=%(here)s

**Comment by ue-it** [comment] 2016-03-01 04:19
It works well with http://127.0.0.1:9001/logtail/test, but not work after nginx with http://my.url/logtail/test   
All the others work well, so I think the problem is not nginx. Can anyone help me to find the reason?

**Comment by alzmcr** [comment] 2016-03-10 12:53
Same problem here as @ue-it - work well locally but not from remote. Anyone aware of the reason?

**Comment by sokokaleb** [comment] 2016-04-03 17:52
Same problem. The page says "Error response. Error code 404. Message: Not Found."

**Comment by samwang1027** [comment] 2016-04-06 02:58
It doesn't not work after nginx with http://my.url/logtail/test. 
The page says "504 Gateway Time-out  nginx/1.6.2".
The fix: https://github.com/Supervisor/supervisor/pull/195/files can not solve my problem.

**Comment by simonegymondo** [comment] 2016-04-06 14:13
I have the same issue but I get

Error response
Error code 410.
Message: Gone.

**Comment by hemantsangwan** [comment] 2016-05-28 06:26
Me too facing the same issue like @simonegymondo

**Comment by arnuschky** [comment] 2016-06-17 12:36
Same here. Nginx 1.10.1 Chome 51.0.2704.79

```2016/06/17 12:34:08 [error] 17986#17986: *10 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XX.XX.XX.XX, server: supervisor.example.com, request: "GET /logtail/crashmail HTTP/1.1", upstream: "http://127.0.0.1:9001/logtail/crashmail", host: "supervisor.example.com", referrer: "https://supervisor.example.com/"
```

**Comment by evgenity** [comment] 2016-08-09 08:21
This fix helped our team: https://github.com/Supervisor/supervisor/pull/195

**Comment by julienfabre** [comment] 2017-07-10 14:00
Had the same issue (404 not found) with nginx 1.10.2.
This Nginx config fixed the problem: https://serverfault.com/a/836855

**Comment by mnaberez** [comment] 2020-09-30 21:31
All of the known issues with the `tail -f` output on the web interface are believed to be fixed as of Supervisor 4.2.0 (released 2020-04-30).  That release includes the most recent fix, for the nginx proxy buffering issue immediately above, that was committed in 7d39a0fea0aa69061c3d2d1474d01559cd18ddfd.

**Closed by mnaberez** 2020-09-30 21:31 UTC
Labels: web

**Comment by xzxiaoshan** [comment] 2025-03-18 03:31
Chrome 134.0.6998.89 version cannot view logs properly


> All of the known issues with the `tail -f` output on the web interface are believed to be fixed as of Supervisor 4.2.0 (released 2020-04-30). That release includes the most recent fix, for the nginx proxy buffering issue immediately above, that was committed in [7d39a0f](https://github.com/Supervisor/supervisor/commit/7d39a0fea0aa69061c3d2d1474d01559cd18ddfd).
