### ISSUE TITLE
supervisorctl expects to talk to a server with API version 3.0, but the remote version is 1.0

### ISSUE THREAD

**Issue by openstack-test** [Supervisor/supervisor#1343] opened 2020-04-12 05:57 UTC
Env
1）# cat /etc/redhat-release 
CentOS release 6.10 (Final)

2）# pip list |grep supervisor
supervisor      4.1.0  

Issue
1）# supervisorctl status
Sorry, this version of supervisorctl expects to talk to a server with API version 3.0, but the remote version is 1.0.

I also have this problem with supervisor 3.3.4, I don't know how to solve it, I need help, thank you

**Comment by mnaberez** [comment] 2020-04-12 06:59
Here's what I tried to reproduce this:
```
$ python3 -m venv venv/

$ venv/bin/pip install supervisor
Collecting supervisor
  Downloading https://files.pythonhosted.org/packages/ca/1f/07713b0e1e34c312450878801d496bce8b9eff5ea9e70d41ff4e299b2df5/supervisor-4.1.0-py2.py3-none-any.whl (318kB)
     |████████████████████████████████| 327kB 1.6MB/s 
Installing collected packages: supervisor
Successfully installed supervisor-4.1.0

$ venv/bin/supervisord --version
4.1.0

$ cat supervisord.conf
[supervisord]
nodaemon = true

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat 

$ venv/bin/supervisord -c supervisord.conf 
2020-04-11 23:56:09,387 INFO Increased RLIMIT_NOFILE limit to 1024
2020-04-11 23:56:09,394 INFO RPC interface 'supervisor' initialized
2020-04-11 23:56:09,394 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2020-04-11 23:56:09,395 INFO supervisord started with pid 26266
2020-04-11 23:56:10,402 INFO spawned: 'cat' with pid 26271
2020-04-11 23:56:11,404 INFO success: cat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

In another terminal:
```
$ venv/bin/supervisorctl status
cat                              RUNNING   pid 26271, uptime 0:01:23
```

I am going to close this issue because I can't reproduce it.  If you can provide instructions showing how to reproduce it, we can reopen.

**Closed by mnaberez** 2020-04-12 06:59 UTC
