### ISSUE TITLE
supervisord process cpu use very high

### ISSUE THREAD

**Issue by xhhan** [Supervisor/supervisor#1612] opened 2023-12-08 06:52 UTC
# Environment:
Supervisord versions: 3.3.2 and 4.2.4
OS system: Debian 8.9

# Behavior:
The CPU usage of the supervisord process is very high (80%-90%).
I ran strace and found a lot of "gettimeofday" calls.
I performed profiling and found the following trace: "supervisord.py (runforever) -> process.py (transition) -> time_time -> gettimeofday". This trace may indicate a problem.
It seems like the process is constantly checking the status, leading to high CPU usage. What should I do to address this?

**Comment by xhhan** [comment] 2023-12-19 03:58
emmm

**Comment by mnaberez** [comment] 2023-12-19 16:41
Duplicate of #807

**Closed by mnaberez** 2023-12-19 16:41 UTC
