### ISSUE TITLE
supervisorctl should return 1 when upcheck() fails

### ISSUE THREAD

**Issue by jhershberg** [Supervisor/supervisor#1209] opened 2019-03-03 12:24 UTC
In a number of scenarios, e.g., the unix domain socket specified in --serverurl is not present, supervisorctl will exit with status 0. Standard convention would be to return 1.

Reproducible by running: supervisorctl --serverurl file:///this/path/does/not/exist status

**Comment by mnaberez** [comment] 2019-03-03 12:27
Duplicate of #24 

This has been fixed in the current master branch, and will be released in Supervisor 4.0.

**Closed by mnaberez** 2019-03-03 12:27 UTC
Labels: supervisorctl
