### ISSUE TITLE
"supervisorctl start xxx"command stuck

### ISSUE THREAD

**Issue by Flyalay** [Supervisor/supervisor#942] opened 2017-06-04 02:53 UTC
Hello everybody
I had a problem with supversior 3.2.0 on ubuntu:
When running  "supervisorctl start xxx"command will be stuck.
The strace supervisorctl and supervisord processes found that supervisorctl stuck in recvform calls
Analysis supervisord log, it is because there is no send a message, so supervisorctl has been blocked.
Correct behavior seems to be supervisord will reply message "HTTP / 1.1 200 OK", supervisorctl exit after receiving.
I don't know if anyone have this problem, thank you very much for any help.

Good log (excerpt) :
Supervisord:
Recvfrom (5, "POST/RPC2 HTTP / 1.1 \ r \ nHost: local"..., 4096, 0, NULL) = 362
Sendto (5, "HTTP / 1.1 200 OK \ r \ nDate: Sat, 03 J"..., 251, 0, NULL, 0) = 251
Recvfrom (5, ", 4096, 0, NULL, NULL) = 0
Close (5)

Supervisorctl:
The socket (PF_LOCAL, SOCK_STREAM, 0) = 3
Connect (3, {sa_family = AF_LOCAL, sun_path = "/ var/run/supervisor.") = 0
Sendto (3, "POST/RPC2 HTTP / 1.1 \ r \ nHost: local"..., 362, 0, NULL, 0) = 362
Recvfrom (3, "H", 1, 0, NULL) = 1
Recvfrom (3, "T", 1, 0, NULL) = 1
Recvfrom (3, "T", 1, 0, NULL) = 1
Recvfrom (3, P, 1, 0, NULL, NULL) = 1
...

Stuck log (excerpt) :
Supervisord:
Recvfrom (5, "POST/RPC2 HTTP / 1.1 \ r \ nHost: local"..., 4096, 0, NULL) = 362
Recvfrom (5, ", 4096, 0, NULL, NULL) = 0
Close (5) = 0

Supervisorctl:
The socket (PF_LOCAL, SOCK_STREAM, 0) = 3
Connect (3, {sa_family = AF_LOCAL, sun_path = "/ var/run/supervisor.") = 0
Sendto (3, "POST/RPC2 HTTP / 1.1 \ r \ nHost: local"..., 362, 0, NULL, 0) = 362
Recvfrom (3,

**Comment by mnaberez** [comment] 2017-06-04 17:37
When you start a process with `supervisorctl start foo`, the time it takes for the command to finish depends on the value of `startsecs` in the section `[program:foo]`.  `supervisord` will block until the process stays up for as long as `startsecs`.  If `startsecs` is set too high, `supervisord` can block for a long time and `supervisorctl` will appear stuck.

**Comment by Flyalay** [comment] 2017-06-05 02:46
[program: foo] the startsecs value in the configuration is used by default (1s).

Starting foo, supervisord log has a tip:
foo entered RUNNING state, and process has stayed up for > than 1 seconds (startsecs)

When **supervisorctl start foo** stuck, press ctrl + c, then **supervisorctl status foo** show the foo is RUNNING status
It doesn't seem to matter to startsecs value.

Not clear supervisord reply "200 OK" in normal, when stuck just close the socket without sending anything.

**Comment by Flyalay** [comment] 2017-06-08 02:15
I found a way to reproduce the problem.

For example, the host current time is "2017/6/8 17:00"

When the **supervisorctl start foo** is executing, the system time change to  "2017/6/8 16:00"

The **supervisorctl start foo** command is stuck at this time.

**Comment by s19096** [comment] 2017-10-31 18:32
I got the same issue like you said (using supversior 3.2.0 on ubuntu). The problem occurred after I upgraded the kernel to GNU/Linux 4.4.0-98-generic x86_64. I solved this by rollbacking the kernel to GNU/Linux 4.4.0-97-generic x86_64.

**Comment by mnaberez** [comment] 2018-02-17 22:17
Closing this issue in favor of #1043 which has an explanation of the cause and a pull request to fix it.

**Closed by mnaberez** 2018-02-17 22:17 UTC
