### ISSUE TITLE
Feature request: read environment variables from a file

### ISSUE THREAD

**Issue by javilm** [Supervisor/supervisor#1574] opened 2023-02-09 22:21 UTC
I know this has been requested before in #771 and closed, but I'll request it again: 

Please implement the ability to read the environment variables for a process from a file.

**Use case**

I have a number of Flask applications running under Supervisor. These applications have secrets that can't be commited to GitHub, such as database passwords, session secrets, etc. Because of this, the applications read these secrets from environment variables during initialization.

Currently, adding a new secret requires editing the `supervisord.conf` file. My users can't do that by themselves because they don't have admin access on this application server.

**Alternatives**

There are ways to work around this limitation in supervisor, such as:

1. Add code to the application so it reads the secrets from a file on startup
2. Set up a secrets management tool such as Hashicorp Vault

Both of these add complexity (a lot in the case of Vault) that could be avoided by implementing this functionality in supervisor.

**Comment by mnaberez** [comment] 2023-02-09 22:31
Moved to https://github.com/Supervisor/supervisor/issues/771#issuecomment-1424923818

Please do not intentionally open duplicates of existing issues.  

Duplicate of #771

**Closed by mnaberez** 2023-02-09 22:31 UTC
