### ISSUE TITLE
Termination of supervisor after (regular or abnormal) termination of process

### ISSUE THREAD

**Issue by hadmut** [Supervisor/supervisor#1340] opened 2020-04-01 12:52 UTC
Hi, 

YES, I am fully aware of issue #712 and that all issues around the problem of terminating supervisord after one of it's subprocesses terminated is a frequently asked question which always will be ignored by triaging as a duplicate of #712. 

However: #712 is not a solution. It's an ugly and cumbersome workaround to have a separate python process just to tell to stop. 

Since supervisord is more and more often used in docker images, which expect to have a single responsible task to terminate after beeing finished or having a problem, and it should be easy to implement, it should be possible to have a configuration option for programs that simply tells supervisor to terminate (with all living children) after a process has terminated 
- in any case
- in an abnormal way where it wouldn't be restarted or
- after the given number of restarting tries has failed. 

Having a separate process just to tell supervisor 'it's over now' is not a clean style and just a workaround for the moment. Since #712 is more than four years old, there should have been a clean solution meanwhile. And after all, terminating supervisord and it's children (as if it had received a ctrl-c/signal) should already exist as a function, it just needs to be called if the function is set. 

regards

**Comment by mnaberez** [comment] 2020-04-01 14:48
Duplicate of #712

**Closed by mnaberez** 2020-04-01 14:48 UTC
