### ISSUE TITLE
Unwanted restart when modifying config

### ISSUE THREAD

**Issue by mrx23dot** [Supervisor/supervisor#1637] opened 2024-03-23 19:39 UTC
I have an existing simple entry
```
[program:test]
command=..
```

on the next app error I didn't want to restart it, so I would have a chance to check stderr of real cause,
(since next start would override stderr)

so I added 
```
autorestart=false
then
sudo supervisorctl update
```

**but this restarted the program!** 
`uptime 0:00:03`

I don't think this restart is wanted.
Programs can be part of critical infrastructure, and we should be able to modify parameters without affecting current instance. (maybe if command changed then it would justified, but even then it's questionable)

**Comment by mnaberez** [comment] 2024-03-24 01:53
Duplicate of #214

**Closed by mnaberez** 2024-03-24 01:53 UTC
