### ISSUE TITLE
Is it possible to get Supervisord to log output from custom pipes other than stdout and stderr?

### ISSUE THREAD

**Issue by lkrubner** [Supervisor/supervisor#988] opened 2017-09-12 21:54 UTC
I have an app that has 4 pipes:

stdout

stderr

email_failure

database_query

Is there any way I can get Supervisord to listen to all 4, and write the output to 4 different logs? Obviously stdout and stderr are easy, but the other two? 

If this feature doesn't exist, can it be added in the future?

**Comment by mnaberez** [comment] 2017-09-13 00:43
> Is there any way I can get Supervisord to listen to all 4, and write the output to 4 different logs? Obviously stdout and stderr are easy, but the other two?

No, it only supports `stdout` and `stderr`.

> If this feature doesn't exist, can it be added in the future?

Duplicate of #379

**Closed by mnaberez** 2017-09-13 00:43 UTC
Labels: logging
