### ISSUE TITLE
refresh not working via apache proxy

### ISSUE THREAD

**Issue by mboeru** [Supervisor/supervisor#251] opened 2013-07-01 13:51 UTC
I have setup the web interface of supervisor to run on 127.0.0.1:9001, and I have setup a reverse proxy in apache so I can load the webpage via apache.
the page would be accesible at http://my.domain.ext/supervisor/

Now when I try to refresh the web page via the refresh button I get sent to 

http://my.domain.ext/supervisor/index.html?action=refresh

which in turn redirects me to

http://127.0.0.1:9001/?message=Page%20refreshed%20at%20Mon%20Jul%20%201%2016%3A46%3A22%202013

which of course it does not work

The same thing happens when I press stop all, or stop/start/restart on each service.

**Comment by bierdok** [comment] 2015-02-15 14:03
+1 same issue

**Comment by bierdok** [comment] 2015-02-15 14:09
@tlatorre-uchicago just add ```proxy_set_header Host $http_host/index.html;``` do the trick!
Thank a lot for this simple nice hack.

**Comment by Paul424** [comment] 2015-06-18 21:19
I've had the same issue; the proxy_redirect directive just would not match the location i expect from supervisord (i expect localhost:9111) but found only matches on http:// (so far...).

I got it solved by changing the host:

proxy_set_header        Host localhost;

**Comment by ulrith** [comment] 2016-09-20 08:04
It looks like there is a bug when use supervisord web interface behind nginx proxy with HTTPS scheme. The redirection after click on buttons goes to HTTP urls instead of HTTPS in spite of `proxy_set_header X-Forwarded-Proto $scheme;` used in nginx config. Could it be fixed?

**Comment by wooyek** [comment] 2016-12-06 10:11
This is because actual sheme is ignored: 

https://github.com/Supervisor/supervisor/blob/91d909c54f118b1848ec644fad601a82c7126fd8/supervisor/http.py#L308

and `cgi_environment` will never set `HTTPS` or `SERVER_PORT_SECURE` headers. Any header not included explicitly will get a `HTTP_` prefix:

https://github.com/Supervisor/supervisor/blob/91d909c54f118b1848ec644fad601a82c7126fd8/supervisor/http.py#L297

**Comment by mnaberez** [comment] 2020-09-30 21:43
Closing as duplicate of #29 which describes the same problem and is also linked from many related issues.  It should be resolved when #593 or similar is merged.

**Closed by mnaberez** 2020-09-30 21:43 UTC
Labels: web

**Comment by fengsi** [comment] 2020-09-30 22:42
Great.  7+ years have passed and this minor issue is still not fixed/merged.

Nowadays, sadly, ~~pretty much nobody~~ not everyone is still interested in using supervisor. 🤦
