### ISSUE TITLE
Run docker in supervisor

### ISSUE THREAD

**Issue by vallsv** [Supervisor/supervisor#1476] opened 2021-12-01 16:59 UTC
Hi,

I would like to be able to launch and stop a docker defined as a program in supervisor config.

Here is the kind of command i use.

```
[program:activemq]
command=bash -c "sudo docker run --rm --name activemq -p 8161:8161 -p 61613:61613 activemq:main"
startsecs=2
startretries=1
autostart=true
redirect_stderr=true
priority=500
killasgroup=true
stopasgroup=true
```

But obviously it is not able to stop or to restart the program, cause `docker stop` have to be called instead of a `SIGINT`.

Do you have any hint on how this could be done.

I probably can find my way with a script wrapper, but there is maybe already better ways?
I am not a specialist of docker, any information could be very useful.

Thanks a lot.

**Comment by vallsv** [comment] 2021-12-02 09:53
Here is something working with a shell script wrapper.
It calls `docker stop` when receiving `SIGUSR1`.

I have used `USR1` instead of default signals, so what i still can kill manually stuffs if needed.

I am still interested in simpler solution.

```
#! /bin/bash
# Wrapper to run and stop properly a docker container with Supervisor
#
# The first argument have to be the name of the container, other parameters
# are passed to a "sudo docker run" command.
#
# "sudo docker stop CONTAINER_NAME" is called with a SIGUSR1 is received.
#
# The supervisor program have to be setup with "stopsignal=USR1"

# Separator inside supervisor logs
T=$(date +%R)
echo "$T mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"

NAME=$1
ARGS=${@:2}
PID=$$

echo "PID: ${PID}"

shutdown()
{
    CMD="sudo docker stop ${NAME}"
    echo "EXEC: ${CMD}"
    ${CMD}
    exit 0
}

echo 'wrapper' > /proc/$$/comm

trap 'shutdown' SIGUSR1

CMD="sudo docker run --name ${NAME} ${ARGS}"
echo "EXEC: ${CMD}"
${CMD} &  # The & is mandatory to be able to catch the signal
wait
```
I have rewritten my program description the following way:
```
[program:activemq]
command=bash -c "./docker-run.sh activemq --rm -p 8161:8161 -p 61613:61613 activemq:main"
startsecs=2
startretries=1
autostart=true
redirect_stderr=true
priority=500
stopsignal=USR1
```

**Comment by mnaberez** [comment] 2021-12-08 18:38
> Here is something working with a shell script wrapper.
> It calls docker stop when receiving SIGUSR1.
> 
> I have used USR1 instead of default signals, so what i still can kill manually stuffs if needed.
> 
> I am still interested in simpler solution.

Thanks for following up with this solution.  The Supervisor developers do not have enough bandwidth to assist with running particular programs under supervisord, sorry.  I'm going to close this issue because it's not a bug in supervisord.  However, others should feel free to comment below with any alternate solutions.

**Closed by mnaberez** 2021-12-08 18:38 UTC
Labels: question
