### ISSUE TITLE
gracefull restart for a group

### ISSUE THREAD

**Issue by freeseacher** [Supervisor/supervisor#731] opened 2016-03-17 17:42 UTC
Hi! 
Is it possible to add command for gracefull restart. i have several daemons written in python and django and sometimes i need to restart my app for applying new code. 
It will be great iа ш can restart them one by one. somethng like
```restart web:* gracefull ```
witch will kill them one by one. so i will allways have at least one still working

tnx!

**Comment by freeseacher** [comment] 2016-04-06 13:13
any news ?

**Comment by mnaberez** [comment] 2016-07-25 17:10
Duplicate of #53.

**Closed by mnaberez** 2016-07-25 17:10 UTC
Labels: question, signals
