### ISSUE TITLE
PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.

### ISSUE THREAD

**Issue by xiebruce** [Supervisor/supervisor#1214] opened 2019-03-14 18:27 UTC
supervisor version: 3.1.4
python version: 2.7.5

supervisor can start by running `supervisord -c /etc/supervisord.conf`, but it showed up the following warning:
```
 root > / > etc > supervisord.d > supervisord -c /etc/supervisord.conf
/usr/lib/python2.7/site-packages/supervisor/options.py:383: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  return pkg_resources.EntryPoint.parse("x="+spec).load(False)
Unlinking stale socket /var/run/supervisor/supervisor.sock
```

**Comment by mnaberez** [comment] 2019-03-14 18:32
Duplicate of #617.  This was [fixed in Supervisor 3.2.0](https://github.com/Supervisor/supervisor/blob/3.2.0/CHANGES.txt#L49-L50), which was released on 2015-11-30.

**Closed by mnaberez** 2019-03-14 18:32 UTC
Labels: packaging
