### ISSUE TITLE
unix:///tmp/supervisor.sock refused connection

### ISSUE THREAD

**Issue by luolingchun** [Supervisor/supervisor#1249] opened 2019-06-11 07:47 UTC
version：alpine：3.9；supervisor：4.0.3

In the 18.09.5 environment of docker version, supervisorctl will appear：**unix:///tmp/supervisor.sock refused connection**

but not in the 1.12.3 environment of docker version.

Is this a docker bug or a supervisor bug?

**Comment by mnaberez** [comment] 2019-06-11 13:57
Here's what I tried to reproduce this.

Config file with a `[unix_http_server]`:

```
[supervisord]
nodaemon=true 

[unix_http_server]
file=/tmp/supervisor.sock   

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:cat]
command=/bin/cat
```

Start `supervisord` in the foreground with that config:

```
$ supervisord --version
4.0.3 

$ supervisord -n -c ./supervisord.conf 
```

In another terminal, try `supervisorctl`:

```
$ supervisorctl -c ./supervisord.conf status
cat                              RUNNING   pid 18825, uptime 0:00:06
```

Above, it shows that `supervisorctl` can communicate with `supervisord` using the socket file defined in `[unix_http_server]`.

I'm going to close this issue since I can't reproduce it.  If you can provide instructions similar to the above that show a problem, we can reopen.

**Closed by mnaberez** 2019-06-11 13:57 UTC
