### ISSUE TITLE
[BUG] Supervisor cannot parse paths with a dot

### ISSUE THREAD

**Issue by dizcza** [Supervisor/supervisor#1389] opened 2020-11-21 14:22 UTC
Pay attention to **/root/.hashcat** dir path with a dot.

Works:

```
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
startsecs=0
stdout_logfile = /root/hashcat/wpa-server/logs/supervisor/nginx_stdout.log
stderr_logfile = /root/hashcat/wpa-server/logs/supervisor/nginx_stderr.log
autostart=true
autorestart=true
```

Doesn't work:

```
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
startsecs=0
stdout_logfile = /root/.hashcat/wpa-server/logs/supervisor/nginx_stdout.log
stderr_logfile = /root/.hashcat/wpa-server/logs/supervisor/nginx_stderr.log
autostart=true
autorestart=true
```

Traceback:
```
Error: The directory named as part of the path /root/.hashcat/wpa-server/logs/supervisor/nginx_stdout.log does not exist. in section 'program:nginx' (file: '/etc/supervisor/conf.d/hashcat_wpa.conf')
```

Assuming, of course, that I create the respective log folders. Tried wrapping in `"`; didn't help.

```
# supervisord -v
3.3.1
# uname -a
Linux 7e1ae03ea423 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mnaberez** [comment] 2020-11-21 21:00
> Error: The directory named as part of the path /root/.hashcat/wpa-server/logs/supervisor/nginx_stdout.log does not exist. in section 'program:nginx' (file: '/etc/supervisor/conf.d/hashcat_wpa.conf')

This error message from `supervisord` intends to convey that `supervisord` expects a directory to exist but the directory does not exist.  `supervisord` does not create log directories.  

Given this in a `[program:x]` section:

    stdout_logfile = /root/.hashcat/wpa-server/logs/supervisor/nginx_stdout.log

This directory must exist:

    /root/.hashcat/wpa-server/logs/supervisor

If any part of that path does not exist, the error message shown above will be given.  The solution is to create the directory `/root/.hashcat/wpa-server/logs/supervisor` before starting `supervisord`. 

I attempted to reproduce the bug as described ("Supervisor cannot parse paths with a dot"):

```
$ supervisord --version 
4.2.1 

$ cat supervisord.conf 
[supervisord]

[program:cat]
command = /bin/cat
stdout_logfile = /root/.hashcat/wpa-server/logs/supervisor/stdout.log

$ ls /root/.hashcat/wpa-server/logs/supervisor
ls: /root/.hashcat/wpa-server/logs/supervisor: No such file or directory

$ supervisord -n -c supervisord.conf 
Error: The directory named as part of the path /root/.hashcat/wpa-server/logs/supervisor/stdout.log does not exist in section 'program:cat' (file: 'supervisord.conf')
For help, use /usr/local/bin/supervisord -h

$ mkdir -p /root/.hashcat/wpa-server/logs/supervisor

$ supervisord -n -c supervisord.conf 
2020-11-21 12:40:01,613 INFO Increased RLIMIT_NOFILE limit to 1024
2020-11-21 12:40:01,618 INFO supervisord started with pid 84597
2020-11-21 12:40:02,625 INFO spawned: 'cat' with pid 84600
2020-11-21 12:40:03,628 INFO success: cat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

I found that when the directory did not exist, `supervisord` behaved as expected and showed the same error message as the original report.  After I created the directory, `supervisord` started successfully and created the log file.  Since I could not reproduce a bug here, I am going to close this issue.

**Closed by mnaberez** 2020-11-21 21:00 UTC
Labels: logging
