### ISSUE TITLE
Better support for logrotate

### ISSUE THREAD

**Issue by opoplawski** [Supervisor/supervisor#1090] opened 2018-04-10 16:27 UTC
The Fedora supervisor project provides a logrotate script to rotate the supervisor logs.  This is desirable because it is good to have consistent log rotation policy (days, naming, etc) across all daemons on the system.  However, there is no lightweight mechanism to notify supervisor that the logs have been rotated.  You can send SIGHUP, but this will restart all of the child processes, which may not be desired.  Although this may be the only way for them to write to new logs as well.

**Comment by opoplawski** [comment] 2018-04-10 16:29
See also https://bugzilla.redhat.com/show_bug.cgi?id=1565747

**Comment by mnaberez** [comment] 2018-04-10 16:38
Duplicate of #273

**Closed by mnaberez** 2018-04-10 16:38 UTC
Labels: logging
