### ISSUE TITLE
Add option to exit supervisord if a program exits or can't restart

### ISSUE THREAD

**Issue by frankjas** [Supervisor/supervisor#1373] opened 2020-09-24 23:15 UTC
If supervisord is managing processes in a container and is set as the entrypoint in no-daemon mode then under certain circumstances it is desirable to have supervisord exit if a certain process exits.  For example, consider a container offering an HTTP api implemented in Python.  The container may have nginx, uwsgi, and a python daemon performing the app logic.

nginx and uwsgi should be restarted automatically, but if for some reason they can't restart then the container should exit since it no longer can serve HTTP requests.

The proposal is to add a config option for each process section which when true would trigger  a supervisord exit.

**Comment by mnaberez** [comment] 2020-09-24 23:18
Duplicate of #712

**Closed by mnaberez** 2020-09-24 23:18 UTC
