### ISSUE TITLE
Update not work

### ISSUE THREAD

**Issue by pysnow530** [Supervisor/supervisor#1248] opened 2019-06-10 07:43 UTC
Hi there, I change the command in supervisord.conf, but after I tried reread, reload, and update, it seems the command didn't updated.

The process is restarted, but the command is not changed successfully.

If this is a bug, or what command could I use?

Any information could I submit?

**Comment by mnaberez** [comment] 2019-06-11 00:36
Here's what I tried to reproduce this.

```
$ supervisord --version
4.0.3 

$ cat supervisord.conf
[supervisord]
nodaemon=true 

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat

$ supervisord -c ./supervisord.conf
2019-06-10 17:25:22,006 INFO Increased RLIMIT_NOFILE limit to 1024
2019-06-10 17:25:22,020 INFO RPC interface 'supervisor' initialized
2019-06-10 17:25:22,020 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2019-06-10 17:25:22,020 INFO supervisord started with pid 15802
2019-06-10 17:25:23,024 INFO spawned: 'cat' with pid 15805
2019-06-10 17:25:24,026 INFO success: cat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Leave `supervisord` running.  

In another terminal, change `command=/bin/cat` to `command=/bin/dog` in the config file and then issue the update command:

```
$ tail -3 supervisord.conf 
[program:cat]
command = /bin/dog

$ supervisorctl -c supervisord.conf update
cat: stopped
cat: updated process group
```

Above, `supervisorctl` shows that the process was updated.  Confirming in the `supervisord` output:

```
2019-06-10 17:28:45,880 INFO waiting for cat to stop
2019-06-10 17:28:45,881 INFO stopped: cat (terminated by SIGTERM)
2019-06-10 17:28:46,887 INFO spawnerr: can't find command '/bin/dog'
```

The change was detected and updated accordingly.

I'm going to close this issue because I can't reproduce it.  If you can provide instructions similar to the above that shows `update` does not work, we can reopen.

**Closed by mnaberez** 2019-06-11 00:36 UTC
