### ISSUE TITLE
be able to specify a custom shutdown/stop command/script in the [program:x] config section

### ISSUE THREAD

**Issue by rafaeltuelho** [Supervisor/supervisor#639] opened 2015-07-29 19:54 UTC
In the [program:x] configuration sections there are two properties related to stop process. According to documentation Supervisord pass the SIGTEM (or other signal) to the managed child process. 

Some applications/services requires custom steps (eg. cleanup resources) before to gracefully. I such scenario would be nice have the ability to specify a custom command/script in the [program:x] config. section.

Somethnig like:
```
[program:myprogram]
...
stopcommand=/service/path/service_shutdown.sh
...
```

That make sense?

**Comment by mnaberez** [comment] 2015-07-29 20:00
Duplicate of #147.

**Closed by mnaberez** 2015-07-29 20:00 UTC

**Comment by rafaeltuelho** [comment] 2015-07-29 20:17
ops! sorry :-/

**Comment by AngeIII** [comment] 2017-10-24 07:26
@mnaberez We understand that this is duplicate, however 5 years.. why still no such command available?

**Comment by mnaberez** [comment] 2017-10-24 15:47
> We understand that this is duplicate, however 5 years.. why still no such command available?

https://github.com/Supervisor/supervisor/issues/147#issuecomment-52440691

**Comment by Lzjing-1997** [comment] 2024-11-21 08:15
12 years ~
