### ISSUE TITLE
'supervisorctl reread' exits with 0 status code with broken config

### ISSUE THREAD

**Issue by adamchainz** [Supervisor/supervisor#902] opened 2017-03-09 18:23 UTC
If I want to test the validity of a config without starting it right now, it seems like I should run `reread`. However this isn't great for automated systems as it doesn't exit with non-zero status code on error:

```
# echo 'aoisretnaoirstnoairstne' > /etc/supervisor/conf.d/foo.conf
# supervisorctl reread
ERROR: CANT_REREAD: File contains no section headers.
file: /etc/supervisor/conf.d/foo.conf, line: 1
'aoisretnaoirstnoairstne\n'
# echo $?
0
```

It would appear that instead of checking status code, one should check for 'ERROR' at the start of the output, which is fragile.

This is contrary to the behaviour of `update`, which exits with '2' if its 'reread' fails:

```
# supervisorctl update
error: <class 'xmlrpclib.Fault'>, <Fault 92: "CANT_REREAD: File contains no section headers.\nfile: /etc/supervisor/conf.d/foo.conf, line: 1\n'aoisretnaoirstnoairstne\\n'">: file: /usr/lib64/python2.7/xmlrpclib.py line: 800
# echo $?
2
```

I think if there's an error in the config, 'reread' should exit with the same status 'update' does.

Checked on version 3.3.1.

**Comment by mnaberez** [comment] 2017-03-09 18:27
Duplicate of #24.  This has been fixed on the master branch which will be Supervisor 4.0.

**Closed by mnaberez** 2017-03-09 18:27 UTC

**Comment by adamchainz** [comment] 2017-03-09 18:32
Just figured that out by looking at the source. Thanks!
