### ISSUE TITLE
supervisior not auto create stdout_logfile

### ISSUE THREAD

**Issue by BlackSinny** [Supervisor/supervisor#1573] opened 2023-02-09 09:07 UTC
## my supervisor conf file like this
```conf
[program:xxxsrv]
directory=/data/projects/xxxsrv/
command=/data/projects/xxxsrv/xxxsrv -config=/data/projects/xxxsrv/qcloud.toml
stdout_logfile=/data/log/xxxsrv/xxxsrv.log
stdout_logfile_backups=50
redirect_stderr=true
autostart=true
autorestart=true
```
## when i run command
```bash
supervisorctl restart xxxsrv
```
server running successfully,but nothing my log file ** /data/log/xxxsrv/xxxsrv.log **

## when i touch file,everything is ok
```bash
vim /data/log/xxxsrv/xxxsrv.log
```
## my question
Should I have to manually create log files every time I start a new project？

when i mkdir log dir,file will created autoly

**Comment by mnaberez** [comment] 2023-02-09 17:17
> when i mkdir log dir,file will created autoly

Duplicate of #120

**Closed by mnaberez** 2023-02-09 17:17 UTC
Labels: logging

**Comment by BlackSinny** [comment] 2023-02-10 01:58
Maybe I wasn't clear enough yesterday, I created the directory before running, but supervisor didn't automatically create log files after the restart
- this is miss directory error msg
```bash
error: <class 'xmlrpclib.Fault'>, <Fault 92: "CANT_REREAD: The directory named as part of the path /data/log/testsrv/testsrv.log does not exist in section 'program:test_srv' (file: '/etc/supervisord.d/test_srv.ini')">: file: /usr/lib64/python2.7/xmlrpclib.py line: 794
```
