### ISSUE TITLE
unix:///var/run/supervisor.sock no such file - The Return

### ISSUE THREAD

**Issue by ServerMonkey** [Supervisor/supervisor#1409] opened 2021-02-17 10:20 UTC
I know this is an old issue. https://github.com/Supervisor/supervisor/issues/480
But it shows up again.
I am on Kali Linux 2020.4 VirtualBox image from:
https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-image-download/#1572305786534-030ce714-cc3b

After a clean installation with `apt install supervisor`
I get: _unix:///var/run/supervisor.sock no such file_
To solve this I run this old trick:
```
sudo touch /var/run/supervisor.sock
sudo chmod 777 /var/run/supervisor.sock
sudo service supervisor restart
```
But once I reboot the system the supervisor.sock files disappears.
And I have to use `touch and chmod` again.

I tried changing the location of file= and serverurl= in supervisord.conf, to different locations.
But the file always disappears no matter where I save it to.

**Comment by mnaberez** [comment] 2021-02-17 13:12
Duplicate of #480

**Closed by mnaberez** 2021-02-17 13:12 UTC
