### ISSUE TITLE
supervisord always starts processes on add and update

### ISSUE THREAD

**Issue by dtrodrigues** [Supervisor/supervisor#1124] opened 2018-07-18 00:42 UTC
When adding a new configuration file to a directory listed within the [include] directive, I need to be able to make supervisord aware of the service so that I can later call `supervisorctl start servicename`. When I do `supervisorctl reread servicename` it notifies that `servicename: available`. 

When `supervisorctl start servicename` is run, the output is `servicename: ERROR (no such process)`. If I try to do a `supervisorctl add servicename`, the service starts. If I instead do `supervisorctl update servicename`, the service also starts. 

I know that autostart is the default behavior, and I do want this service autostarted if supervisord itself were to be restarted (or stopped and started), but at the point that I'm initially adding the service, I do not want the service to start. Is there any way to do `add` or `update` or another command, possibly with a flag, in order to make a new service available to be run without actually running it?

**Comment by mnaberez** [comment] 2018-07-18 00:49
Duplicate of #214

**Closed as completed by mnaberez** 2018-07-18 00:49 UTC
