### ISSUE TITLE
modify configure file and restart supervisord

### ISSUE THREAD

**Issue by luxin88** [Supervisor/supervisor#1031] opened 2017-12-22 01:15 UTC
when I modify the pid file path, and restart supervisord, old process will read the new pid file path, no doubt, the old pid file is not in the new path. So it throw an error that pid file not found!

**Comment by Drugoy** [comment] 2018-10-16 10:38
How is that supervisor's problem?
IMO it's your problem and you should stop your processes manually before making supervisord re-read the config and then manually start the jobs again, but according to the new config.
I don't think supervisord maintainers have to do any changes in that regard.

**Comment by mnaberez** [comment] 2019-03-13 21:40
Duplicate of #441

**Closed by mnaberez** 2019-03-13 21:40 UTC
