### ISSUE TITLE
feature: add optional attribute to only start process, when required processes reached RUNNING state.

### ISSUE THREAD

**Issue by michaelhammann** [Supervisor/supervisor#1450] opened 2021-07-16 11:11 UTC
For my use case it would be useful to only start a process after dependent process reaches RUNNING state if the optional process config parameter depends_on is used. Starting processes consecutively using a priority is not enough in my case. 
This feature requires the dependent process to be set to RUNNING state correctly and therefore depends on #1446.

I am using supervisor 4.2.2. and I also created a suggestion for the implementation here: #1449

Appreciate your help!

**Comment by mnaberez** [comment] 2021-07-19 00:08
Duplicate of #122

**Closed by mnaberez** 2021-07-19 00:08 UTC
