### ISSUE TITLE
backend process not work，supervisor：CRIT uncaptured python exception

### ISSUE THREAD

**Issue by lyddragon** [Supervisor/supervisor#876] opened 2017-01-12 12:40 UTC
request："GET /..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c..%c1%1c../windows/win.ini HTTP/1.1" 

supervisor log：
2017-01-12 20:35:14,367 CRIT uncaptured python exception, closing channel <POutputDispatcher at 24325224 for <Subprocess at 24276048 with name 8080 in state RUNNING> (stdout)> (<type 'exceptions.UnicodeDecodeError'>:'utf8' codec can't decode byte 0xc1 in position 25: invalid start byte [/usr/lib/python2.7/site-packages/supervisor-4.0.0.dev0-py2.7.egg/supervisor/supervisord.py|runforever|223] [/usr/lib/python2.7/site-packages/supervisor-4.0.0.dev0-py2.7.egg/supervisor/dispatchers.py|handle_read_event|260] [/usr/lib/python2.7/site-packages/supervisor-4.0.0.dev0-py2.7.egg/supervisor/options.py|readfd|1525] [/usr/lib/python2.7/site-packages/supervisor-4.0.0.dev0-py2.7.egg/supervisor/compat.py|as_string|23] [/usr/lib64/python2.7/encodings/utf_8.py|decode|16])

**Comment by mnaberez** [comment] 2017-01-12 16:40
Duplicate of #638.

You are using the master branch but since you are running Python 2, you could use a stable release version of Supervisor instead.  The current release version, [Supervisor 3.3.1](https://pypi.python.org/pypi/supervisor/3.3.1), does not have this bug.

**Closed by mnaberez** 2017-01-12 16:40 UTC
Labels: logging
