### ISSUE TITLE
supervisord giving up to start proces is wrong only checking  startretries without time duration

### ISSUE THREAD

**Issue by ryanlyy** [Supervisor/supervisor#1109] opened 2018-06-12 08:21 UTC
In Suppervisord configure file on program, there is startretries parameter but there is no duration time. it is possible that program restart startretries  with long long time duration. But suppervisord now does not care duration instead of only checking startretries.  I think it is not correct. Supervisord shall decide to give up when it tries to start it startretries  times within duration time. for example: if supervisord failed to start it 3 times within 30s, then it can give up.

**Comment by mnaberez** [comment] 2018-06-12 16:39
Duplicate of #487

**Closed by mnaberez** 2018-06-12 16:39 UTC
