### ISSUE TITLE
Feature request: load program env vars from a file

### ISSUE THREAD

**Issue by jhoblitt** [Supervisor/supervisor#882] opened 2017-01-19 16:28 UTC
Many software packages include a "sysconf" file (`/etc/default/<foo> /etc/sysconfig/<foo>`) of environment variables for their init scripts.  It would be a great convenience if `supervisor` had the ability to initialize a program's environment from this well known format.  Essentially, an equivalent to systemd's [`EnvironmentFile`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=).

**Comment by mnaberez** [comment] 2017-01-19 17:07
Duplicate of #242.

**Closed by mnaberez** 2017-01-19 17:07 UTC
Labels: environment
