### ISSUE TITLE
Feature request: start delay and dependencies

### ISSUE THREAD

**Issue by tonic12** [Supervisor/supervisor#1336] opened 2020-03-12 07:39 UTC
Hi!

I think supervisord need add two very important features:

- start delay - many times i need start some prepare scripts before runing main process.
- start dependencies - i want start main process only if another program was started

EXAMPLE:
```
[program:consul_configure]
command=/consul/consul_configure.sh
redirect_stderr=true
priority=1

[program:consul]
**startdelaysecs=3**
command=/consul/consul agent -config-dir /consul/config
autorestart=true
redirect_stderr=true
priority=2

[program:ha_template]
command=/consul/consul-template -config "/consul/template/ha_template.hcl"
autorestart=true
redirect_stderr=true
priority=3
**dependencies=program:consul**

[program:ha_config]
command=/consul/consul-template -config "/consul/template/ha_config.hcl"
autorestart=true
redirect_stderr=true
priority=4
**dependencies=program:consul**


[program:haproxy]
command=haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -W
stopsignal=SIGUSR1
stopwaitsecs=10
autorestart=true
redirect_stderr=true
priority=999
**dependencies=program:ha_template, program:ha_config**
```

In that's example if consul was not start, don't need run another programs. Before consul start configuration script and create config.

**Comment by mnaberez** [comment] 2020-03-12 17:11
> start delay - many times i need start some prepare scripts before runing main process.

Duplicate of #487

> start dependencies - i want start main process only if another program was started

Duplicate of #122

**Closed by mnaberez** 2020-03-12 17:11 UTC
