### ISSUE TITLE
Make possible to disable activity log to stdout

### ISSUE THREAD

**Issue by vpal** [Supervisor/supervisor#821] opened 2016-09-07 11:43 UTC
This is kind of a feature request / question.

I just started using supervisord with docker.
I'm trying to use Nginx with some script that manages nginx restarts on configuration changes in a single container.

I'm trying to achieve that only nginx logs appear in the docker logs output.
So I would like docker to only collect the logs of nginx and not the logs of supervisord.

I haven't found any way to achieve this based on the documentation.
Despite that I provide the logfile in the [supervisord] section or on the command line when I start the container I also see the messages of supervisord besides the Nginx logs.
So supervisord logs to both it's log file and stdout and I would expect it to only log to the log files or at least being able to configure this.

Of course because of docker supervisord is started in foreground.

Thanks in advance.

**Comment by mnaberez** [comment] 2016-09-07 13:35
Duplicate of #661.

**Closed by mnaberez** 2016-09-07 13:35 UTC
Labels: logging
