### ISSUE TITLE
Kill supervisord once all processes it is running exited successfully in docker

### ISSUE THREAD

**Issue by suhasckanade** [Supervisor/supervisor#1369] opened 2020-08-26 04:45 UTC
We have 3 python processes running inside a docker using supervisord. I have found when all program gets exited successfully still my container is running as supervisord process is running which is the main PID1.

`CMD ["/usr/bin/supervisord"]`

How can I kill/stop supervisord, so that container will automatically pull down?

**Comment by mnaberez** [comment] 2020-08-26 04:49
Duplicate of #712

**Closed by mnaberez** 2020-08-26 04:49 UTC

**Comment by suhasckanade** [comment] 2020-08-26 05:00
I went through the #712 before adding this new issue here. #712 is mostly killing supervisord when one of the any process is stop/killed. 
But I need to stop supervisord when all processes are exited successfully. Could you please assist, how #712 I can use for here?

**Comment by mnaberez** [comment] 2020-08-26 14:48
> But I need to stop supervisord when all processes are exited successfully.

`supervisord` does not have any built-in feature to automatically shut it self down based on various conditions.  An eventlistener could be written to do it, similar to the one shown in #712.  We still have #712 open and are using it to track requests related to this.
