### ISSUE TITLE
Dependencies of starting between programs

### ISSUE THREAD

**Issue by FAKERINHEART** [Supervisor/supervisor#805] opened 2016-08-03 07:17 UTC
There are two programs A and B, and I wanna start A strictly after B. What can I do for this kind of requirements?
I found that setting priorities for programs A and B in their supervisor config files did not promise their starting order.
3Q~

**Comment by mikeyg123** [comment] 2016-08-03 11:04
We have a similar issue but we're building the dependency information and scheduling into a tool that then calls supervisor to do the start/stop actions.

**Comment by mnaberez** [comment] 2016-08-03 14:17
Duplicate of #122.

**Closed by mnaberez** 2016-08-03 14:17 UTC
