### ISSUE TITLE
Create /var/log/supervisor/ if not exists

### ISSUE THREAD

**Issue by pompushko** [Supervisor/supervisor#1644] opened 2024-05-08 22:14 UTC
Hello

I facing one issue, when I have clean folder `/var/log/`
Is there any solution except to create every boot time folder `/var/log/supervisor/`

```
piwpiw@piwpiw:/opt/piw $ /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist
For help, use /usr/bin/supervisord -h
```

Thank you!

**Comment by mnaberez** [comment] 2024-05-08 22:18
Duplicate of #120

**Closed by mnaberez** 2024-05-08 22:18 UTC
