### ISSUE TITLE
Unexpected lock of a process

### ISSUE THREAD

**Issue by enVolt** [Supervisor/supervisor#829] opened 2016-09-24 15:31 UTC
I've few Laravel's consumer process running via supervisor. Here is how my supervisor config looks like

```
[program:process_m]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/user/public_html/artisan process:message
autostart=true
autorestart=true
;user=apache
numprocs=1
redirect_stderr=true
stdout_logfile=/home/user/worker.log
```

This task are stopping unexpectedly. From the log stream of process, it looks like the process has just stopped working, but `supervisorctl status` says that process is in `RUNNING` state. Then I added log statement almost after each line of code, to pin point the issue (My assumption was that it was something related to command). But nothing is getting logged.

`strace` result for that particular process says

```
[~]> sudo strace -p 15548
Process 15548 attached
write(3, "Processed: Illuminate\\Queue\\Call"..., 51^CProcess 15548 detached
 <detached ...>
```

This particular log statement is generated as `stdout` by the command (not logged by process to log files)

The process is locked here. It's not ending, so it's not restarting, neither it's in running state despite supervisor status being `RUNNING`.

What could possibly be wrong here? Is it something system specific? What can I do to avoid this?

**Comment by mnaberez** [comment] 2016-09-24 15:50
> This task are stopping unexpectedly. From the log stream of process, it looks like the process has just stopped working, but supervisorctl status says that process is in RUNNING state. 

Does the command `supervisorctl status` work when the process is in this state?  If that hangs or doesn't connect, it might indicate a problem in `supervisord`.  If `supervisorctl` commands work normally, that almost always indicates something is wrong with the process running under `supervisord` (as opposed to a bug in `supervisord` itself).

> The process is locked here. It's not ending, so it's not restarting, neither it's in running state despite supervisor status being RUNNING.

The `RUNNING` state only means the process stayed up long enough to exit the `STARTING` state, and the process hasn't terminated.  If you run `supervisorctl pid <processname>` and get a pid, you can see the process running with tools like `ps`.  `supervisord` doesn't have any knowledge of what your process might want to do, so `RUNNING` doesn't imply your program is doing what it's supposed to.

**Comment by enVolt** [comment] 2016-09-24 17:44
`supervisorctl status` is working fine. To be honest, I'm not sure if it is something related to supervisor.

**Comment by mnaberez** [comment] 2016-09-24 18:30
> To be honest, I'm not sure if it is something related to supervisor.

Can you run your process outside of `supervisord` for a while (e.g. in a `screen` session)?  If it hangs there too, that would eliminate `supervisord`.

**Comment by enVolt** [comment] 2016-09-25 05:27
This log statement
> Processed: Illuminate\\Queue\\Call

is generated as stdout by process, and writing it to a log file (`/home/user/worker.log`) is part of `supervisord`, and strace output suggest that a write operation to a file is blocked (fd is 3), that's why I've a feeling that it might be related to supervisor. I've tried running the process in background via screen. No such problem there (basis on screen output, it crashes because of some error (application part; intended behaviour))

**Comment by mnaberez** [comment] 2016-09-25 06:34
> No such problem there (basis on screen output, it crashes because of some error (application part; intended behaviour))

I don't know what to make of this because on the one hand you're saying your program runs fine under `screen` but you're also saying it crashes under `screen`, so maybe it's just not running long enough to get into its "stuck" state.

I haven't seen anything in this ticket that leads me to believe there's a problem with `supervisord` yet.  You said that `supervisorctl status` works means `supervisord` isn't hang up.  It's always possible there's a bug in `supervisord` but I don't see one here yet.  I think we'd need more evidence or reproduce instructions to do anything more with this.

**Comment by mnaberez** [comment] 2016-09-26 23:23
What version of Supervisor is this?

You could try [`loglevel=blat`](https://github.com/Supervisor/supervisor/blob/e73d0174339d182ead9c7b26a7c9dae9649f8b00/supervisor/loggers.py#L26) in the `[supervisord]` section of the config file.  `supervisord` logs messages about log activity and file descriptor changes; perhaps something in there will be interesting.

**Comment by enVolt** [comment] 2016-09-27 04:54
Version is `3.2.3`, In `/etc/supervisord.conf` I've changed `loglevel=blather`. I'll post output from log file here, next time when it happens.

**Comment by enVolt** [comment] 2016-09-29 06:22
It hasn't happen since, the only change I can think of was increasing the `fd` limit to 4096 (`ulimit -n 4096`, which some how seem to be reverted), I'll update here as soon as it happens again. 

(I just wish my weekend doesn't get ruined because of it)

**Comment by mnaberez** [comment] 2016-11-14 18:00
Closing due to lack of activity.

**Closed** 2016-11-14 18:00 UTC
Labels: question

**Comment by MazzMazz** [comment] 2018-06-28 11:59
@mnaberez  it would be very interesting how you solved this. It happens for me too.

Laravel Jobs with access to a Amazon FIFO queue
