### ISSUE TITLE
How to specify the syslog facility?

### ISSUE THREAD

**Issue by hany** [Supervisor/supervisor#887] opened 2017-02-09 13:29 UTC
Hi there, thanks so much for this project by the way. We use it *extensively*. I'm looking to configure Supervisor to log to `syslog`, but I'm not sure how we can specify the *facility* supervisor logs to? I have a custom logger setup on `local1`, but I can't see a way to tell Supervisor to use it.

**Comment by mnaberez** [comment] 2017-02-09 17:37
Duplicate of #814.

**Closed by mnaberez** 2017-02-09 17:37 UTC
Labels: question, syslog
