### ISSUE TITLE
Read environment variables from file

### ISSUE THREAD

**Issue by standa4** [Supervisor/supervisor#771] opened 2016-06-13 14:02 UTC
Hello,

is it possible read the environment variables from file or are you planning to add this feature?
It would be useful in case where I have multiple applications managed by supervisord and these applications share the same env vars. I don't want to edit multiple conf files. These variables can be stored in one file and read from it. 

Thank you.

**Comment by mnaberez** [comment] 2016-06-13 14:39
There is an `environment=` option in the [`[supervisord]`](http://supervisord.org/configuration.html#supervisord-section-values) section.  Put the variables in the `[supervisord]` section and they will be inherited by all subprocesses.

**Closed by mnaberez** 2016-06-13 14:39 UTC
Labels: environment

**Comment by Choms** [comment] 2018-08-28 12:18
Hi,

This is not an appropriate answer, you are not only not answering to @standa4's question, but you are also treating him in a condescending way, like if he was stupid enough as for not reading the documentation that clearly states how to use the `environment` line...

I'll exemplify his request with another example I think would be more helpful on depicting the issue... let's say I have a bash script with a conditional that checks some system parameters, and based on that sets one env with a value or a different one that I'll use in my program... it would be really helpful to be able of sourcing that file from the supervisord configuration file. (inb4 just create a bash wrapper that executes your program and call the wrapper from supervisord)

Now the **actual** question was "are you planning to add this feature?" - Can we please get a yes/no answer (I'm guessing it's a "no" based on the date of this issue and the other related issues that were closed too), and, if you feel generous enough, an argument for your decision?

Thanks

**Comment by mnaberez** [comment] 2018-08-28 21:37
> This is not an appropriate answer, you are not only not answering to @standa4's question, but you are also treating him in a condescending way, like if he was stupid enough as for not reading the documentation that clearly states how to use the environment line...

[The question](https://github.com/Supervisor/supervisor/issues/771#issue-159957429) asked for a single place to define environment variables, citing a desire to not modify multiple config files.  Putting the variables in `[supervisord]` section of the root config file seems to meet those requirements.   There are two places that `environment=` can be specified in the config file(s).  One is any `[program:x]` section where the variables will be applied only to that program.  The other is in the `[supervisord]` section, where the variables will inherited by all programs.  My response was intended to be helpful, not condescending.  There's a lot of documentation, and it's easy to miss details like this.

> Now the actual question was "are you planning to add this feature?" - Can we please get a yes/no answer (I'm guessing it's a "no" based on the date of this issue and the other related issues that were closed too), and, if you feel generous enough, an argument for your decision?

There are not currently plans to add a separate type of config file just for environment variables.  Since this has already been discussed in other issues, please refer to those issues.

**Comment by frutik** [comment] 2020-02-15 11:43
what a stupid answer

**Comment by frutik** [comment] 2020-02-15 11:50
you can achieve similar effect with
```
command=sh -c ". ./app-env && bundle exec unicorn -c unicorn.rb"
stopasgroup=true
killasgroup=true
```

**Comment by mnaberez** [comment] 2020-02-15 17:42
Constructive comments are welcome but abusive ones will be removed from the issue tracker.

**Comment by stephendwolff** [comment] 2020-09-21 14:24
I came to this question - thinking that the original poster meant literally from a file ie a `.env` file as other applications use, rather than the environment variables being shared by supervisord itself. So, i suspect this is not solved, and the OP just got fed up!

**Comment by ericholscher** [comment] 2020-10-15 16:39
Agreed. Not being able to read this data from a file is a pretty big missing feature. I have a standard way of defining the env for all my programs, except supervisord. I'd +1 adding functionality for this.

**Comment by szthanatos** [comment] 2020-10-30 07:47
Same question.
How to get variables from a `.env` file instead of write everything into supervisor conf file.
It make me feel like living in Classical-Python2-Age.

**Comment by aaronbriel** [comment] 2020-12-10 15:22
I've had to work around this by executing a bash script in the command that sources my .env file.

**Comment by ospalax** [comment] 2020-12-16 11:03
I don't know how others are treating theirs supervisor's config files (service inis) but I am trying to use them as generic as possible and if some service needs to have env populated with some service specific variables then I want to (need to) source them somehow from envfile.

Your answer is to hard-wire env vars inside the service config file??

There are already existing use-cases like this sshd service in the form of systemd unit:
```
[Service]
Type=notify
EnvironmentFile=-/etc/crypto-policies/back-ends/opensshserver.config
EnvironmentFile=-/etc/sysconfig/sshd
ExecStart=/usr/sbin/sshd -D $OPTIONS $CRYPTO_POLICY
ExecReload=/bin/kill -HUP $MAINPID
```

**Comment by CallMarl** [comment] 2021-02-25 18:37
> J'ai dû contourner ce problème en exécutant un script bash dans la commande qui source mon fichier .env.

Can you please share command detail?

**Comment by ShivKJ** [comment] 2021-08-19 08:09
Is it resolved?

**Comment by rrauenza** [comment] 2021-12-02 16:07
Explaining a use case for this -- hashicorp's vault drops secrets into files.  I'd like to be able to drop some authentication keys as a .env file with root only read permissions and have supervisord pick those up when I restart the service.

(I don't want vault messing with the supervisord config files directly.)

I think the only workaround is command='/bin/sh -c "source /var/lib/vault/secret.env && run_my_service"'

**Comment by thisven** [comment] 2021-12-18 12:21
Thanks for sharing that workaround. As long as there are no plans on implementing the appreciated variable for service files, this is kind of a consolation.

**Comment by balanikaran** [comment] 2022-05-10 06:42
Hey, is this feature in pipeline?

**Comment by benzkji** [comment] 2022-05-12 08:23
There are many use cases for this, .env files are widely used nowadays, I dont see a reason to not implement it. Also, specifying the vars under `[supervisord]` is by far not a solution, as normaly, each program is supposed to have it's own .env.

**Comment by benzkji** [comment] 2022-05-12 08:24
@balanikaran no, the issue is currently closed. Fingers crossed this gets a revival some day!

**Comment by benzkji** [comment] 2022-05-12 08:58
another real argument is the "secret" nature of .env files, they often get their content out of an encrpyted file, and just cannot be written directly into a supervisor config file. as @rrauenza indirectly shows in his example.

anyway, thanks for listening ;-)

**Comment by mnaberez** [comment] 2023-02-09 22:30
Moved from #1574 
> I know this has been requested before in #771 and closed, but I'll request it again:
> 
> Please implement the ability to read the environment variables for a process from a file.
> 
> Use case
> 
> I have a number of Flask applications running under Supervisor. These applications have secrets that can't be commited to GitHub, such as database passwords, session secrets, etc. Because of this, the applications read these secrets from environment variables during initialization.
> 
> Currently, adding a new secret requires editing the supervisord.conf file. My users can't do that by themselves because they don't have admin access on this application server.
> 
> Alternatives
> 
> There are ways to work around this limitation in supervisor, such as:
> 
>     Add code to the application so it reads the secrets from a file on startup
>     Set up a secrets management tool such as Hashicorp Vault
> 
> Both of these add complexity (a lot in the case of Vault) that could be avoided by implementing this functionality in supervisor.

**Comment by hevisko** [comment] 2023-02-24 11:44
Scrolling through this, having similar need(s)
I suspect the real answer is:  `Do the needed work & code and present a pull request`

**Comment by benzkji** [comment] 2023-02-24 11:54
@hevisko no exactly :-) As this issue has been closed, you'll need to check possibilities to have it merged, otherwise you'll do it for yourself and your frustration only.

As @mnaberez states, there are no plans developing this feature...that could mean no plans to merge a PR, or not...

**Comment by prashnts** [comment] 2023-04-19 17:55
Sorry to add another comment in this old thread, but this is the top google search result.

Just in case it helps, I structure my `.env` files as bash scripts, so I could set my `command` to `source .env && do-something`.
