### ISSUE TITLE
Adding additional paths to environment does not work correctly

### ISSUE THREAD

**Issue by lukepolo** [Supervisor/supervisor#1169] opened 2018-11-07 18:57 UTC
supervisord : 3.2.0
python : 2.7.12

Ive been trying to set PATH variables inside the environment config so we can run a command easily. While I could put the full path , it seem this should work. But it does not.

```bash
[program:server-daemon-1]
directory=/home/codepier/varie.io/current
process_name=%(program_name)s_%(process_num)02d
command=laravel-echo-server
autostart=true
autorestart=true
user=codepier
numprocs=1
redirect_stderr=true
stdout_logfile=/home/codepier/workers/server-worker-1.log
stopasgroup=true
stopsignal=QUIT
environment=PATH=/opt/.nvm/versions/node/v10.13.0/bin:%(ENV_PATH)s
```

NOTE : I've tried `environment=PATH="/opt/.nvm/versions/node/v10.13.0/bin:%(ENV_PATH)s"`

I have confirmed this is the location and able to run with full path : 

```bash
pwd
/opt/.nvm/versions/node/v10.13.0/bin

ls
laravel-echo-server  node  npm  npx

/opt/.nvm/versions/node/v10.13.0/bin/laravel-echo-server // runs perfectly
```

Here is additional commands that I've ran 

![image](https://user-images.githubusercontent.com/2066668/48153673-d3211d00-e294-11e8-8a74-5b0b17c86869.png)

I believe this to be a bug, but not 100% sure.

**Comment by mnaberez** [comment] 2018-11-07 19:07
Duplicate of #787 

This has been fixed in ae6f8c99dabb9fad9d044337e4372a0f028a00d8 and will be released in the next version (Supervisor 3.3.5).

**Closed by mnaberez** 2018-11-07 19:07 UTC
Labels: environment, question

**Comment by lukepolo** [comment] 2018-11-07 20:52
For a temp fix , I should be able to add this to whatever shell executes the start of the service ?

`service supervisor start`  as `root` would use roots ... `profile`? 

Struggling to find who actually starts it but it seems to all pointing to root.

**Comment by mnaberez** [comment] 2018-11-07 23:47
> service supervisor start as root would use roots ... profile?

The Supervisor project itself only publishes Python packages to [PyPI](https://pypi.org/project/supervisor/).  Our packages don't have any operating system integration (e.g. `service supervisor start`).  If you installed Supervisor using a distribution package manager like `apt` or `rpm`, the authors of that package have done the integration.  They are third parties that aren't involved with the main Supervisor project, so you'd need to ask them how the package works, sorry.  You could also try asking on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users), perhaps there are some users there running the same package that could help.
