### ISSUE TITLE
Supervisord process use my disk space every second

### ISSUE THREAD

**Issue by hongchialong** [Supervisor/supervisor#1311] opened 2019-12-18 05:17 UTC
**Supervisord version**: 4.1.0
**Supervisord installed by**: easy_install2.7
**Linux**: centOS 6.10
**Supervisor config**: All are default value, only change supervisord's user to root.
**My program config file**: 
```
[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php72 /src/project/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
user=apache
numprocs=3
redirect_stderr=true
```

**Problem description**:
I run supervisord service by the command `supervisord -c /etc/supervisord.conf`, and everything works fine. But one day later, I found the disk space becomes 99%, I don't know why and when I kill supervisord process, it all becomes normal.
And I run supervisord service again, and use `df` command to check the disk space, I found the available is decreasing about 300KBs every second.

I used supervisord before in Ubuntu 18.04 and everything works fine. This is my first to face the problem in centOS.

Do you guys know why did this happen? And how can I solve it? Thanks.

**Comment by Alex-CodeLab** [comment] 2020-01-03 14:32
Check if it is writing something to the (error) log file. 
`/var/log/supervisor/...`

**Comment by hongchialong** [comment] 2020-01-05 11:31
@Alex-CodeLab Thanks for replying. I checked. There are no logs file generated.

**Comment by mnaberez** [comment] 2020-01-06 14:37
> I don't know why and when I kill supervisord process, it all becomes normal.

This may also indicate that the problem is a process running under `supervisord` since when `supervisord` is shut down, all processes running under `supervisord` should shut down also.  

> The log file is quite normal, no error message.

`supervisord` should not use any appreciable disk space except for the log files.  If the log files are not large then it's unlikely that the disk space is being used by `supervisord` itself.  I think it is more likely that a process running under `supervisord` is using the disk space.  

I am going to close this issue because I do not think it is a bug in `supervisord`.  If you can provide reproduce instructions that show `supervisord` is indeed using large amounts of disk unrelated to the log files, we can reopen.

**Closed by mnaberez** 2020-01-06 14:37 UTC
