### ISSUE TITLE
/logtail/<program> returns a 404 when inet_http_server run behind a reverse proxy, via a sub-path

### ISSUE THREAD

**Issue by kartick** [Supervisor/supervisor#929] opened 2017-04-27 01:10 UTC
1. Setup, and run nginx as reverse proxy, proxying to http://127.0.0.1:9001 and responding to requests coming on `/supervisor` (see attached config).
2. Fire up the browser and access http://127.0.0.1/supervisor (this will show the web UI correctly), links like stop, restart, work
3. Click the "Tail -f" link for any supervisor "program" listed on the UI -> Returns a 404

[default.txt](https://github.com/Supervisor/supervisor/files/960151/default.txt)

**Comment by mnaberez** [comment] 2017-04-27 01:15
Duplicate of #29.

**Closed by mnaberez** 2017-04-27 01:15 UTC

**Comment by kartick** [comment] 2017-04-27 01:21
@mnaberez I see there are several related issues to this one (#929). Any idea when the fix for this issue will be incorporated?
