### ISSUE TITLE
Install by pip show error message

### ISSUE THREAD

**Issue by jotagesales** [Supervisor/supervisor#1095] opened 2018-04-24 11:23 UTC
When install supervisor by pip with python 3
``` pip install supervisor```

Show this error message:
``` 
Complete output from command python setup.py egg_info:
Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.6.3 (default, Apr 11 2018, 22:57:54)
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)].  Please install using a supported version.
```

But if try install by git is working:
```pip install git+https://github.com/Supervisor/supervisor.git```

**Comment by mnaberez** [comment] 2018-04-24 15:26
Duplicate of #1060

**Closed by mnaberez** 2018-04-24 15:27 UTC
Labels: python 3
