### ISSUE TITLE
Python 3 Support Mis-information

### ISSUE THREAD

**Issue by jerryji** [Supervisor/supervisor#1127] opened 2018-07-30 13:37 UTC
> Supervisor is intended to work on Python 3 version 3.4 or later ...

I wonder why the above is prominently displayed on github while pip3 install fails --

```
$ pip3 install supervisor
Collecting supervisor
  Downloading https://files.pythonhosted.org/packages/44/60/698e54b4a4a9b956b2d709b4b7b676119c833d811d53ee2500f1b5e96dc3/supervisor-3.3.4.tar.gz (419kB)
    100% |████████████████████████████████| 419kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.6.5 (default, Apr  1 2018, 05:46:30)
    [GCC 7.3.0].  Please install using a supported version.
```

**Comment by mnaberez** [comment] 2018-07-30 16:06
Duplicate of #1060

**Closed by mnaberez** 2018-07-30 16:06 UTC
Labels: python 3

**Comment by jerryji** [comment] 2018-08-02 01:30
This is not a duplicate case, it's about a bug in README.rst

**Comment by mnaberez** [comment] 2018-08-03 16:49
I marked it as a duplicate of #1060 because the same question was already asked and [answered there](https://github.com/Supervisor/supervisor/issues/1060#issuecomment-377702224).
