### ISSUE TITLE
[Help Wanted] Log process' output to file as well as console

### ISSUE THREAD

**Issue by vidhu** [Supervisor/supervisor#1139] opened 2018-08-22 20:13 UTC
I have a child process running with supervisord in a docker container. I want to save the log to a file and also output it to the console.

Currently I'm having to write my config file like this:

```[supervisord]
nodaemon=true

[program:dos-ping]
command=ping 1.1.1.1
autostart=true
autorestart=true
stdout_logfile=/var/log/ping.stdout.log
stderr_logfile=/var/log/ping.stderr.log

[program:ping-stdout]
command=tail -f /var/log/ping.stdout.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:ping-stderr]
command=tail -f /var/log/ping.stderr.log
stdout_logfile=/dev/stderr
stdout_logfile_maxbytes=0
```

I want to be able to do `docker logs <container id>` to be able to see my logs.
I also want the logs to be saved in a file

Is there a better way to do this?

**Comment by mnaberez** [comment] 2018-08-24 18:17
Duplicate of #849

**Closed by mnaberez** 2018-08-24 18:17 UTC
Labels: logging, question
