### ISSUE TITLE
high CPU usage and epoll Poller

### ISSUE THREAD

**Issue by aleph0naught** [Supervisor/supervisor#1515] opened 2022-06-22 11:18 UTC
Hi! 

We found high CPU consumption (our java application 70%, supervisor 30%) when using supervisor
After running strace, it turned out that this consumption is associated with redirecting application's stdout to log file - supervisor using system calls read/write/select in python2 and poll in python3 - and apparently the main cpu time is spent on select syscall. Also we can't use kqueue since we use ubuntu

We need logs, so we want to reduce CPU consumption without turning them off
So far, the only thing that comes to mind is using epoll instead of select/poll to wait for descriptors in the hope that it will help

Are there any plans to add epoll to pollers list?
If so, when will it happen? And if not, is it worth adding its support on my own? Are there any pitfalls here?

Or maybe you can suggest how to solve this problem in some other way?

**Comment by mnaberez** [comment] 2022-06-22 15:08
Duplicate of #807

**Closed by mnaberez** 2022-06-22 15:08 UTC

**Comment by aleph0naught** [comment] 2022-06-22 15:33
@mnaberez

Can you please answer the question about epoll that I asked in this issue?
