### ISSUE TITLE
How to prepend stdout and stderr output lines of process with dates?

### ISSUE THREAD

**Issue by aalexgabi** [Supervisor/supervisor#773] opened 2016-06-15 16:54 UTC
A process has its stdout and stderr output logged into separate files. How to prepend the date for each line in the output to be able to know when each line has been generated?

If this feature doesn't exist or there is no robust workaround consider this issue a feature request.

**Comment by mnaberez** [comment] 2016-06-21 14:27
Duplicate of #553.

**Closed by mnaberez** 2016-06-21 14:27 UTC
