### ISSUE TITLE
Supervisor at 100% CPU

### ISSUE THREAD

**Issue by fliespl** [Supervisor/supervisor#1344] opened 2020-04-17 17:57 UTC
We have just noticed that supervisor master got stuck at 100%.

http://ss.codeone.pl/ss-2020-04-17_19-54-41-1587146081.png

Any idea how can we troubleshoot it more if it's our configuration or some other issue? All jobs look like that:

```
[program:unitown_push_send]
command=php bin/console 'push:send' --verbose --no-debug --env=prod
directory=/var/www/vhosts/xxx/current
autostart=true
autorestart=true
startsecs=5
startretries=999999999
user=owadmin
stdout_logfile=/var/log/supervisor/xxx_push_send.log
stdout_logfile_maxbytes=50MB
redirect_stderr=true
```

```
owadmin@owuln01:~$ supervisord --version
3.3.5
```

```
owadmin@owuln01:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
```

**Comment by mnaberez** [comment] 2020-04-17 18:02
Duplicate of #807

**Closed by mnaberez** 2020-04-17 18:02 UTC
