### ISSUE TITLE
Supervisor daemon fails to start if log directory does not exist

### ISSUE THREAD

**Issue by rzaharenkov** [Supervisor/supervisor#1143] opened 2018-08-30 15:11 UTC
In my opinion supervisor daemon itself should be super reliable and start even if there is any issue with configuration of particular programs.

In my case I am deploying my application in 2 steps:

1. Bootstrap server using `chef` (install packages and create configuration files).
2. Deploy application using `capistrano` (fetches application from github and restart particular services using `supervisorctl restart my_group:*`.

I run 1st step first time when I am bootstrapping new machine or when I do any changes to software or system configuration. 2nd step is running in order to release new version of application code.

So after very first running of `chef` I am ending up with broken supervisor (service is dead) because it can't find directory. Then run `capistrano` in order to deploy application 1st time (it creates all the required directories) and tries to restart services using `supervisorctl` but fails. So I need to run `chef` 1 more time which is inconvenience.

I do believe if something is wrong with single program configuration then supervisor daemon itself should start but program should be in failed state.

**Comment by mnaberez** [comment] 2018-08-30 17:12
Duplicate of #120

**Closed by mnaberez** 2018-08-30 17:12 UTC
Labels: logging

**Comment by rzaharenkov** [comment] 2018-09-06 11:38
@mnaberez, I am talking here about create log directory automatically. I aim is to ignore this error because it's not critical. Imagine you have 100 programs in the config and only 1 references to a directory that doesn't exist. What should happen? I think it's more than logic the daemon should start, print warning message to the log and mark 1 program as failed.

**Comment by mnaberez** [comment] 2018-09-07 20:15
> I aim is to ignore this error because it's not critical. Imagine you have 100 programs in the config and only 1 references to a directory that doesn't exist. What should happen?

https://github.com/Supervisor/supervisor/issues/120#issuecomment-379437855
