### ISSUE TITLE
Starting process groups does not honour autorestart and restarts indefinitely

### ISSUE THREAD

**Issue by jonathantullett** [Supervisor/supervisor#574] opened 2015-02-09 11:37 UTC
I have discovered an issue whereby starting a process via by doing

    supervisor> start procgroup:*

does not honour the autorestart settings and results in supervisor trying to restart any failed processes in that group indefinitely.

My test-case config file:
    
    [program:test]
    command=/tmp/exit-non-zero.sh
    autostart=false
    autorestart=false
    startsecs=3

    [group:mytest]
    programs=test

/tmp/exit-non-zero.sh contains:

    #!/bin/bash
    sleep 1
    exit 1

Then I run the test:

    supervisor> start mytest:test
    mytest:test: ERROR (abnormal termination)
    supervisor> start mytest:*

At this point it keeps respawning. The logs contain:
> 2015-02-09 11:32:53,037 INFO spawned: 'test' with pid 11913
> 2015-02-09 11:32:54,060 INFO exited: test (exit status 1; not expected)
> 2015-02-09 11:32:54,124 INFO gave up: test entered FATAL state, too many start retries too quickly
> 2015-02-09 11:32:55,135 INFO spawned: 'test' with pid 11915
> 2015-02-09 11:32:56,151 INFO exited: test (exit status 1; not expected)
> 2015-02-09 11:32:57,153 INFO gave up: test entered FATAL state, too many start retries too quickly
> 2015-02-09 11:32:58,162 INFO spawned: 'test' with pid 11919
> 2015-02-09 11:32:59,183 INFO exited: test (exit status 1; not expected)
> 2015-02-09 11:32:59,249 INFO gave up: test entered FATAL state, too many start retries too quickly
> 2015-02-09 11:33:00,256 INFO spawned: 'test' with pid 11921
> 2015-02-09 11:33:01,313 INFO exited: test (exit status 1; not expected)
> 2015-02-09 11:33:02,315 INFO gave up: test entered FATAL state, too many start retries too quickly

and it continues.

I confirm this is with the latest release of supervisor (3.1.3)

**Comment by jonathantullett** [comment] 2015-02-10 12:11
The issue appears to be within rpcinterface.py, in def startit() (line 276). The spawning part of the process doesn't take into account process.system_stop which is set if the process has exceeded the maxretries parameter, it just respawns indefinitely if runtime < startsecs.

That's as far as I've gotten with the debugging but hopefully it'll help with a speedy resolution.

**Comment by mnaberez** [comment] 2015-07-23 02:34
I added some documentation in d8823432780a48821fb14fc3d410864924acaac8 to explain that `startsecs`/`startretries` applies when the process is in the `STARTING` state and that `autorestart`/`exitcodes` applies when the process is in the `RUNNING` state.  

I followed these instructions on 3.1.3 and on the master branch, and I wasn't able to see anything happen indefinitely.  Your config files doesn't contain `startretries`, so the default of `3` is used.  When I try to start the process or the group, I see the start retries and then it stops trying (log message `gave up`).  Since I wasn't able to get it to do anything indefinitely, I am going to close this issue.

**Comment by jonathantullett** [comment] 2015-07-23 06:05
Using 3.1.3 with the following configuration I still see the same issue:
    [program:test]
    command=/tmp/exit-non-zero.sh              ; the program (relative uses PATH, can take args)
    autostart=false                ; start at supervisord start (default: true)
    autorestart=false               ; whether/when to restart (default: unexpected)
    startsecs=3                   ; number of secs prog must stay running (def. 1)
    startretries=1                ; max # of serial start failures (default 3)
    stdout_logfile=/tmp/test.log        ; stdout log path, NONE for none; default AUTO
    
    [group:mytest]
    programs=test

Running:
    supervisor> start mytest:*

It hangs. It's been sitting here for the past few minutes. The logs are full of:

2015-07-23 07:03:41,769 INFO spawned: 'test' with pid 1044
2015-07-23 07:03:42,782 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712092480 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)
>
2015-07-23 07:03:42,782 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140245712077168 for <Subprocess at 140245712332128 with name test in state STARTING> (stderr
)>
2015-07-23 07:03:42,782 INFO exited: test (exit status 1; not expected)
2015-07-23 07:03:42,782 DEBG received SIGCLD indicating a child quit
2015-07-23 07:03:43,784 INFO gave up: test entered FATAL state, too many start retries too quickly
2015-07-23 07:03:43,805 INFO spawned: 'test' with pid 1046
2015-07-23 07:03:44,820 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712092480 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)
>
2015-07-23 07:03:44,821 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140245712076880 for <Subprocess at 140245712332128 with name test in state STARTING> (stderr)>
2015-07-23 07:03:44,821 INFO exited: test (exit status 1; not expected)
2015-07-23 07:03:44,821 DEBG received SIGCLD indicating a child quit
2015-07-23 07:03:45,827 INFO spawned: 'test' with pid 1048
2015-07-23 07:03:46,842 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712092480 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)>
2015-07-23 07:03:46,842 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140245712079760 for <Subprocess at 140245712332128 with name test in state STARTING> (stderr)>
2015-07-23 07:03:46,843 INFO exited: test (exit status 1; not expected)
2015-07-23 07:03:46,843 DEBG received SIGCLD indicating a child quit
2015-07-23 07:03:47,844 INFO gave up: test entered FATAL state, too many start retries too quickly
2015-07-23 07:03:47,849 INFO spawned: 'test' with pid 1050
2015-07-23 07:03:48,862 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712092480 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)>
2015-07-23 07:03:48,863 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140245712079472 for <Subprocess at 140245712332128 with name test in state STARTING> (stderr)>
2015-07-23 07:03:48,863 INFO exited: test (exit status 1; not expected)
2015-07-23 07:03:48,863 DEBG received SIGCLD indicating a child quit
2015-07-23 07:03:49,868 INFO spawned: 'test' with pid 1052
2015-07-23 07:03:50,882 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712092480 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)>
2015-07-23 07:03:50,882 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140245712079472 for <Subprocess at 140245712332128 with name test in state STARTING> (stderr)>
2015-07-23 07:03:50,883 INFO exited: test (exit status 1; not expected)
2015-07-23 07:03:50,883 DEBG received SIGCLD indicating a child quit
2015-07-23 07:03:51,884 INFO gave up: test entered FATAL state, too many start retries too quickly
2015-07-23 07:03:51,889 INFO spawned: 'test' with pid 1054
2015-07-23 07:03:52,902 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712092480 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)>
2015-07-23 07:03:52,903 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140245712063808 for <Subprocess at 140245712332128 with name test in state STARTING> (stderr)>
2015-07-23 07:03:52,903 INFO exited: test (exit status 1; not expected)
2015-07-23 07:03:52,903 DEBG received SIGCLD indicating a child quit
2015-07-23 07:03:53,909 INFO spawned: 'test' with pid 1056
2015-07-23 07:03:54,921 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712092480 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)>
2015-07-23 07:03:54,921 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140245713096856 for <Subprocess at 140245712332128 with name test in state STARTING> (stderr)>
2015-07-23 07:03:54,922 INFO exited: test (exit status 1; not expected)
2015-07-23 07:03:54,922 DEBG received SIGCLD indicating a child quit
2015-07-23 07:03:54,922 INFO gave up: test entered FATAL state, too many start retries too quickly
2015-07-23 07:03:55,928 INFO spawned: 'test' with pid 1058
2015-07-23 07:03:56,944 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140245712063808 for <Subprocess at 140245712332128 with name test in state STARTING> (stdout)

So this is definitely still an issue, because the 'gave up' doesn't seem to mean it gives up in this instance, it just continues trying.

**Comment by jonathantullett** [comment] 2015-07-23 06:12
However, using 4.0.0.dev0 it's no longer an issue:
> supervisor> start mytest:*
> mytest:test: ERROR (spawn error)

How long until 4.0 is considered release?

**Comment by mnaberez** [comment] 2015-07-23 06:21
Reproduced on 3.1.3

**Comment by mnaberez** [comment] 2015-08-09 00:02
This is fixed on [3.2-branch](https://github.com/Supervisor/supervisor/tree/3.2-branch) and will be in the 3.2.0 release.

**Closed by mnaberez** 2015-08-09 00:02 UTC
