### ISSUE TITLE
Web services often hang up

### ISSUE THREAD

**Issue by pystd** [Supervisor/supervisor#1157] opened 2018-10-14 05:47 UTC
The version of the supervisor I am using is 4.0.0.dev0, and the error log is as follows

`EO 0.0.0.0:uncaptured python exception, closing channel <supervisor.http.supervisor_af_inet_http_server listening 0.0.0.0:9004 at Ox7fl6cde3ld3O> (‘cclass ‘RuntimeError>:dictionary changed size dunn
g iteration runforeverl2l8j (/usr/tocal/lib/python3.5/dist-packages/supervisor-4.0.0.devo-py3.5.egg/supervisor/medusa/asyncore_
25.pylhandte_read_eventl385) (/usr/local/lib/python3.5/dist.packages/supervisor.4.O.0.devo-py3.5.eqg/
supervisor/medusa/http_server.pyl_init_14841 (/usr/local/lib/python3.5/dist-packages/supervisor
-4.0.0.devo-py3.5.egg/supervisor/.edusa/http_server.pylmaintenancel5o2J`

**Comment by vsag96** [comment] 2019-01-21 18:18
How to reproduce this? I use 4.0.0.0.dev0 and never faced any issues? In fact it runs smoothly, can you please share your config file?

**Comment by mnaberez** [comment] 2019-01-21 18:54
From this issue above:

> `(‘cclass ‘RuntimeError>:dictionary changed size dunn g iteration runforeverl2l8j (/usr/tocal/lib/python3.5/dist-packages/supervisor-4.0.0.devo-py3.5.egg/supervisor/medusa/asyncore_ 25.pylhandte_read_eventl385)`

There are some typos but otherwise it looks like the one from #1178:

> (<class 'RuntimeError'>:dictionary changed size during iteration [python3.6/site-packages/supervisor/supervisord.py|runforever|218] [python3.6/site-packages/supervisor/medusa/asyncore_25.py|handle_read_event|385]

That was fixed recently in #1187, so I'll close this issue.

**Closed by mnaberez** 2019-01-21 18:54 UTC
Labels: help wanted
