### ISSUE TITLE
Failure to parse environment with quoted empty strings. (Issue #328)

### ISSUE THREAD

**Issue by mostrows2** [Supervisor/supervisor#873] opened 2017-01-05 00:47 UTC
commit aa7d40e2949043ece15f972a is incorrect...

 The problem is that the test in the above commit tests the value 'foo=""' -- that works.
However, 'foo="",bar=a' will fail.  This seems to be related to the use of "posix=True" with shlex.

#>>> supervisor.datatypes.dict_of_key_value_pairs('foo="",c=d')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mostrows/workspace/cmf.build/agents/cmf/ext-py/supervisor-4.0.0.dev0/supervisor/datatypes.py", line 96, in dict_of_key_value_pairs
    "Unexpected end of key/value pairs in value '%s'" % arg)
ValueError: Unexpected end of key/value pairs in value 'foo="",c=d'
 #>>> supervisor.datatypes.dict_of_key_value_pairs("foo='',c=d")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mostrows/workspace/cmf.build/agents/cmf/ext-py/supervisor-4.0.0.dev0/supervisor/datatypes.py", line 96, in dict_of_key_value_pairs
    "Unexpected end of key/value pairs in value '%s'" % arg)
ValueError: Unexpected end of key/value pairs in value 'foo='',c=d'
#>>> supervisor.datatypes.dict_of_key_value_pairs("foo=''")
{'foo': ''}
#>>> supervisor.datatypes.dict_of_key_value_pairs('foo=""')
{'foo': ''}
#>>>

**Comment by coldnight** [comment] 2017-01-17 02:49
This issue seems caused by the bug of Python, see the detail: 

https://hg.python.org/cpython/rev/cf04243e8d7d

It fixed in Python 2.7.13

**Closed** 2017-01-17 21:32 UTC
Labels: environment
