### ISSUE TITLE
supervisord parsing new lines in logs

### ISSUE THREAD

**Issue by chizou** [Supervisor/supervisor#1242] opened 2019-05-17 21:30 UTC
We have an application that is outputting logs with `\n` characters in them. When supervisord gets these logs and displays the output, it's evaluating the `\n`s and causing multiple lines of output to occur when we originally wanted only one. Since we're feeding our logs into DataDog, it's causing our logs to get polluted with a bunch of individual lines when it shouldn't be. 

**Example output:**
Correct: 
```
[Fri May 17 19:46:23.629839 2019] [php7:notice] [pid 90] [client 10.234.206.61:12348] [2019-05-17 15:46:23] production.NOTICE: array (\n  'message' => 'preparing to decode json payload',\n  'memory_usage' => '4 MB',\n  'size' => '0.31 MB',\n)  \n, referer: https://dev.site.com/
```

supervisord output:
```
[2019-05-17 16:00:05] production.NOTICE: array (
  'message' => 'preparing to decode json payload',
  'memory_usage' => '18 MB',
  'size' => '0 MB',
)
```

How can we get it to stop evaluating the `\n`'s like that?

**Comment by mnaberez** [comment] 2019-05-17 21:48
Here's what I tried to reproduce this.

Python script `echo_slash_n.py`:
```
import sys
import time 

while True:
  sys.stdout.write(r'\n')
  sys.stdout.flush()
  time.sleep(0.1)
```

Config file `supervisord.conf`:
```
[supervisord]

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:echo_slash_n]
command = python3 echo_slash_n.py
startsecs = 0
autorestart = false
stdout_logfile = /tmp/echo_slash_n.log
```

Start `supervisord` in the foreground with that config:
```
$ supervisord -n -c supervisord.conf 
2019-05-17 14:41:25,717 INFO Increased RLIMIT_NOFILE limit to 1024
2019-05-17 14:41:25,731 INFO RPC interface 'supervisor' initialized
2019-05-17 14:41:25,731 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2019-05-17 14:41:25,732 INFO supervisord started with pid 23092
2019-05-17 14:41:26,740 INFO spawned: 'echo_slash_n' with pid 23095
2019-05-17 14:41:26,797 INFO success: echo_slash_n entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
```

In another terminal:
```
$ supervisorctl -c supervisord.conf tail -f echo_slash_n
\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n^C

$ head /tmp/echo_slash_n.log
\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n

$ supervisord --version 
4.0.2 
```

I'm not aware of code in any version of  `supervisord` or `supervisorctl` that would evaluate newlines.  Since I am not able to reproduce it, I am going to close this issue.  If you are able to provide a way to reproduce it similar to the above, we can reopen.

**Closed by mnaberez** 2019-05-17 21:48 UTC
Labels: logging
