### ISSUE TITLE
stdout/stderr flush doesn't work

### ISSUE THREAD

**Issue by Yanpas** [Supervisor/supervisor#951] opened 2017-06-15 15:44 UTC
STR:
1. Create simple python script `run.py`:
```
#!/usr/bin/python
import time
while True:
#for _ in range(5):
	print 'hello'
	time.sleep(1)
exit(1)
```
2. Add it to config
```
[program:py]
command=/home/user/run.py
process_name=run
exitcodes=0
user=user
directory=/home/user/
redirect_stdout=true
stdout_syslog=true
```
3.Start this process
4. `tail -f /var/log/syslog` - nothing in syslog

PS If you replace **while true** with **for loop** five hello messages will be logged as soon as process exits

**Comment by Yanpas** [comment] 2017-06-15 17:51
Seems to be unrelated to syslog, I've added two lines:
```
stdout_logfile_maxbytes=20
stdout_logfile=/home/user/log
```
and removed `stdout_syslog=true`

Instead of file I've create named pipe and ran `cat < log`. Same behavior, there is nothing in pipe

**Comment by mnaberez** [comment] 2017-06-15 18:42
Duplicate of #893.

**Closed by mnaberez** 2017-06-15 18:42 UTC
Labels: logging, syslog

**Comment by Yanpas** [comment] 2017-06-15 18:44
Oh, thanks!
