### ISSUE TITLE
environment didn't take effect on CentOS Linux release 7.3.1611 (Core)

### ISSUE THREAD

**Issue by wenxzhen** [Supervisor/supervisor#1032] opened 2017-12-25 07:46 UTC
I have a ini file under the supervisor specified directory with the following items:
**_environment=JAVA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=6445 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"_**

On the CentOS 7.3, the environement didn't take effect, as I didn't see the options on command line of the running process, but it worked on the CentOS release 6.2 (Final).

Appreciated for any advice.

**Comment by mnaberez** [comment] 2017-12-26 17:20
Here's what I tried to reproduce this.

```
$ supervisord --version
3.3.3

$ cat supervisord.conf
[supervisord]
loglevel=trace

[program:env]
environment=JAVA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=6445 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
command = /usr/bin/env
startsecs = 0
autorestart = false

$ supervisord -n -c supervisord.conf
2017-12-26 09:12:40,866 INFO Increased RLIMIT_NOFILE limit to 1024
2017-12-26 09:12:40,871 INFO supervisord started with pid 17251
2017-12-26 09:12:41,877 INFO spawned: 'env' with pid 17272
2017-12-26 09:12:41,888 DEBG 'env' stdout output:
... many env variables elided ...
JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=6445 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

2017-12-26 09:12:41,889 INFO success: env entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-12-26 09:12:41,889 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 4481461440 for <Subprocess at 4499213952 with name env in state RUNNING> (stdout)>
2017-12-26 09:12:41,889 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 4499282912 for <Subprocess at 4499213952 with name env in state RUNNING> (stderr)>
2017-12-26 09:12:41,889 INFO exited: env (exit status 0; expected)
2017-12-26 09:12:41,890 DEBG received SIGCHLD indicating a child quit
```

Above, `/usr/bin/env` shows that `supervisord` did set `JAVA_OPTS` in the child process environment as expected.  I am going to close this issue since I can't reproduce it.

The CentOS packages mentioned above are created by others not involved with the Supervisor project.  The Supervisor project itself only publishes Python packages to [PyPI](https://pypi.python.org/pypi/supervisor).  If you suspect an issue with the CentOS packages, report the issue to the maintainers of those packages.

**Closed by mnaberez** 2017-12-26 17:20 UTC
Labels: environment
