### ISSUE TITLE
New release with python3?

### ISSUE THREAD

**Issue by sblondon** [Supervisor/supervisor#1174] opened 2018-11-19 22:25 UTC
I'm currently helping another Debian Developer to update the package to the current last release of supervisor (v. 3.3.4) for the next release of Debian. This will be finished soon.

We'd like to know if you plan to release a new version from the master branch with the python3 support. If it's possible, it would be happy to include it in the next release of Debian (in order to switch the dependencies to python3). However, the delay due to [freeze policy](https://release.debian.org/buster/freeze_policy.html) is short so don't hesitate to say if it's not ready or you don't want to release quickly: it's better to include the current release than an unstable new release.

Feel free to do what you want: we don't want to highjack your schedule.

**Comment by mnaberez** [comment] 2018-11-20 07:32
Duplicate of #1060

**Closed by mnaberez** 2018-11-20 07:32 UTC
Labels: python 3

**Comment by mnaberez** [comment] 2018-11-20 07:41
> We'd like to know if you plan to release a new version from the master branch with the python3 support. If it's possible, it would be happy to include it in the next release of Debian (in order to switch the dependencies to python3). 

A future Supervisor 4.0 release that includes Python 3 support is planned, but I do not know if it might be released within your deadlines.  When it is released, it will be available on the [PyPI page](https://pypi.org/project/supervisor/).  That is the source for the stable releases.  I would not recommend packaging any version that is not published to PyPI since only those versions are believed to be stable.
