### ISSUE TITLE
Grand children processes not killed

### ISSUE THREAD

**Issue by monteksingh** [Supervisor/supervisor#1396] opened 2020-12-27 21:47 UTC
My app has a parent process which creates 3 child processes. Each child process inturn creates 4 subprocesses.

When parent process is terminated due to timeout, the child processes and the grandchild processes are not killed, they become orphans.
I am using stopasgroup=true and killasgroup=true in the configuration as well.
supervisor version is 3.2.0 and was installed using sudo apt install supervisor.

Pls help....

**Comment by mnaberez** [comment] 2020-12-29 00:24
Duplicate of #1101

**Closed by mnaberez** 2020-12-29 00:24 UTC

**Comment by monteksingh** [comment] 2020-12-29 03:16
I was not able to find the solution to my problem in the above link. However, I changed the Gunicorn code to kill all children recursively when a worker crashes. This seems to work for now.
