### ISSUE TITLE
I/O operation on closed file

### ISSUE THREAD

**Issue by tmacjx** [Supervisor/supervisor#1011] opened 2017-10-27 11:15 UTC
2017-10-27 19:13:28,550 CRIT uncaptured python exception, closing channel <POutputDispatcher at 21359792 for <Subprocess at 20028664 with name handle_speak in state RUNNING> (stdout)> (<type 'exceptions.ValueError'>:I/O operation on closed file [/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|227] [/usr/local/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/local/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/local/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])

what does this mean?my version is 3.3.3(the latest).THK

**Comment by tmacjx** [comment] 2017-10-27 11:22
my conf:


> [unix_http_server]
> file=/tmp/supervisor.sock   ; (the path to the socket file)
> 
> [supervisord]
> logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
> logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
> logfile_backups=10           ; (num of main logfile rotation backups;default 10)
> loglevel=info                ; (log level;default info; others: debug,warn,trace)
> pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
> nodaemon=false               ; (start in foreground if true;default false)
> minfds=1024                  ; (min. avail startup file descriptors;default 1024)
> minprocs=200                 ; (min. avail process descriptors;default 200)
> 
> [rpcinterface:supervisor]
> supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
> 
> [supervisorctl]
> serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket
> 
> [program:handle_speak]
> numprocs = 1
> user = phenix
> process_name = handle_speak
> directory = /var/www/dream/webapp/handle_speak/
> command = /var/www/dream/env/handle_speak/bin/celery -A manage worker --loglevel=info
> autorestart = true
> redirect_stderr = true
> stdout_logfile = /var/www/dream/handle_speak/var/worker.log
> stderr_logfile = /var/www/dream/handle_speak/var/worker-err.log
> 
> [program:celerybeat]
> numprocs = 1
> user = phenix
> process_name = celerybeat
> directory = /var/www/dream/webapp/handle_speak/
> command = /var/www/dream/env/handle_speak/bin/celery beat -S redbeat.RedBeatScheduler  --loglevel=info
> autorestart = true
> redirect_stderr = true
> stdout_logfile = /var/www/dream/handle_speak/var/celery-beat.log
> stderr_logfile = /var/www/dream/handle_speak/var/celery-beat-err.log
>

**Comment by tmacjx** [comment] 2017-10-27 11:36
My worker do some period tasks, it run almost every second, and I write some logger to an log file.Does this effect?

**Comment by mnaberez** [comment] 2017-10-27 16:23
Duplicate of #984

**Closed by mnaberez** 2017-10-27 16:23 UTC
