### ISSUE TITLE
unable to install supervisor on python 3

### ISSUE THREAD

**Issue by LegitStack** [Supervisor/supervisor#1205] opened 2019-02-19 18:40 UTC
readme says 

> Supervisor is intended to work on Python 3 version 3.4 or later and on Python 2 version 2.7.

I'm on 3.6.4.

I go to http://supervisord.org/ and use the pip install they suggest:

```
sudo python -m pip install --index-url https://pypi.org/simple/ --trusted-host pypi.org supervisor
Collecting supervisor==3.3.5
  Using cached https://files.pythonhosted.org/packages/ba/65/92575a8757ed576beaee59251f64a3287bde82bdc03964b89df9e1d29e1b/supervisor-3.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.6.4 (default, Dec 19 2017, 14:48:12)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)].  Please install using a supported version.
```

> **Supervisor requires Python 2.4 or later but does not work on any version of Python 3.**  You are using version 3.6.4

Am I installing it incorrectly?

**Comment by mnaberez** [comment] 2019-02-19 18:45
Duplicate of #1060

**Closed by mnaberez** 2019-02-19 18:45 UTC
Labels: python 3
