### ISSUE TITLE
Ability to reopen log(s)

### ISSUE THREAD

**Issue by npelov** [Supervisor/supervisor#1609] opened 2023-11-03 10:07 UTC
Some log rotating functions are missing in supervisord. Since implementing all features is not really a viable option logrotate can be used to rotate logs. However there is no command to close and reopen logs to assist log rotation. for example a proper way to rotatelogs would be:

1. (also rotate old logs) 
2. mv name.log name.log.1
3. supervisorctl reopenlogs [process]

I thought reload would do that, but reload actually restarts all processes which is not always wanted behavior.

Technically this can be achieved with syslog, but this way you have to configure both logrotate and systlog which complicates things.

**Comment by mnaberez** [comment] 2023-11-04 23:19
Duplicate of #273

**Closed by mnaberez** 2023-11-04 23:19 UTC
Labels: logging

**Comment by mnaberez** [comment] 2023-11-04 23:21
`supervisord` will reopen its logfiles if it [receives SIGUSR2](http://supervisord.org/running.html?highlight=reopen#signal-handlers).

#273 is a request for a command to trigger rotation.
