### ISSUE TITLE
Chinese garbled output

### ISSUE THREAD

**Issue by sushang123** [Supervisor/supervisor#818] opened 2016-09-02 07:49 UTC
Chinese output in the log is garbled, program parameters in the web interface for the Chinese is garbled, compatible trouble to do next.

**Comment by mnaberez** [comment] 2016-09-02 14:58
Duplicate of #774 or #818.

**Closed by mnaberez** 2016-09-02 14:58 UTC
Labels: web

**Comment by MxdStudio** [comment] 2017-09-08 10:36
i have the same issue
