### ISSUE TITLE
Web interface is very slow

### ISSUE THREAD

**Issue by mondalaci** [Supervisor/supervisor#244] opened 2013-06-13 00:48 UTC
It takes about 1 second to render 10 rows (for 10 processes) on the web interface and refresh gets disturbingly slow when there are dozens of processes to be managed.  It should happen in no time.

**Comment by mnaberez** [comment] 2015-03-26 23:10
This seems to be fixed on master (as of 3fe078a77f0a56903000b0af3283df843fbed598).  Here is what I tried to reproduce it.

Python script `hello.py`:

    import sys
    import time
    while 1:
        sys.stdout.write("hello\n")
        sys.stdout.flush()
        time.sleep(1)    

Minimal `supervisord.conf` to run that script in 50 processes:

    [supervisord]
    logfile = /tmp/supervisord.log
    loglevel = DEBUG
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:hello]
    process_name = hello_%(process_num)d
    command = python /path/to/hello.py
    numprocs=50
    
Run `supervisord` in the foreground with that config:

    $ supervisord -n -c /path/to/supervisord.conf

The web interface displays quickly.  Clicking an action button like "restart all" reloads the page as soon as Supervisor has finished the action.  The improvements can probably be attributed to 9e6aa44a48e1d99e9cf8413cfabe189d1f26fc1f, 50d18577af28b6b053c0d446c959b42b5300a0f8, or other recent changes.  I'm going to close this issue since this looks fixed.

**Closed by mnaberez** 2015-03-26 23:10 UTC
Labels: bug, web
