### ISSUE TITLE
xml-rpc "tailProcessStdoutLog" is not safe with control characters

### ISSUE THREAD

**Issue by perrinjerome** [Supervisor/supervisor#1499] opened 2022-03-22 07:12 UTC
This is similar to #1485 , the problem here is when the process log contain some control characters, like the ansi codes that are sometimes used to make the output on the console use color or bold. These characters are not valid in XML 

If we reuse the reproduction from https://github.com/Supervisor/supervisor/issues/1485#issuecomment-1011809140 but change the `tmp.py` from the example above to:

```python
import time
import logging
l = logging.Logger("a")
while True:
  l.warning('\033[0;31mRed\033[0m')    # this displays "Red", with ansi escape codes to display as red text on the console.
  print(31434134)
  time.sleep(0.01)
```

then the client got a `xml.parsers.expat.ExpatError: not well-formed (invalid token)` error with `tailProcessLog`.

## Some more references:

 * https://www.w3.org/International/questions/qa-controls
 * https://bugs.python.org/issue11804

## Some ideas about a possible fix:

I don't think this is possible if the output is returned as string in XML-RPC , the output has to be returned as a https://docs.python.org/3/library/xmlrpc.client.html#xmlrpc.client.Binary for this to work. Also from API point of view, it's maybe not always OK to treat the program output as text, sometimes program output binary that can not be parsed. The current API interpreting log as text is good for most cases, maybe a new API to get the program *output*, which unlike the program *log* would be the "raw" program output as bytes would address this)

**Comment by mnaberez** [comment] 2022-03-22 07:20
Duplicate of #85

**Closed by mnaberez** 2022-03-22 07:20 UTC

**Comment by perrinjerome** [comment] 2022-03-22 07:31
oh that's interesting, thanks a lot @mnaberez  and sorry for not searching hard enough the existing issues.
