### ISSUE TITLE
Groups should act as namespaces

### ISSUE THREAD

**Issue by johtso** [Supervisor/supervisor#615] opened 2015-05-08 11:34 UTC
It would be fantastic if groups behaved as namespaces.

Currently all groups give you is a way of interacting with programs as a group, and the group name is *required* for referencing the group, but surprisingly they *don't* act as a namespaces!

This means when you have to be constantly away of any possibly conflicting program names in your many `/etc/supervisor/conf.d/*.conf` files, and to be on the safe side, you really need to prefix *all* your program names.

So then you end up with `my-service:my-service-api`.

"Namespaces are one honking great idea -- let's do more of those!"

**Comment by mnaberez** [comment] 2015-07-17 19:58
Closing as a duplicate of #554.  This request isn't exactly a duplicate, but from your comment here and on #554, duplicate section names in your config files is what prompted this request.  We're unlikely to make any major changes to how groups work at this point because it has been like this for many years and may cause issues from some users (config files are only one way processes are created, they can also be created by plugins).  Printing a warning as suggested in #554 would be a way to deal with duplicate sections in the config files without introducing compatibility issues.

**Closed by mnaberez** 2015-07-17 19:58 UTC
