### ISSUE TITLE
ImportError: No module named process

### ISSUE THREAD

**Issue by renukeswarchinta** [Supervisor/supervisor#1272] opened 2019-08-27 08:47 UTC
We are integrating shibboleth module with nginx , in this process we installed supervisor. When we run supervisord service we are getting below error 

```
Aug 26 05:57:41 d1l00313g supervisord: Traceback (most recent call last):
Aug 26 05:57:41 d1l00313g supervisord: File "/usr/bin/supervisord", line 9, in <module>
Aug 26 05:57:41 d1l00313g supervisord: load_entry_point('supervisor==4.0.4', 'console_scripts', 'supervisord')()
Aug 26 05:57:41 d1l00313g supervisord: File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 358, in main
Aug 26 05:57:41 d1l00313g supervisord: File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 368, in go
Aug 26 05:57:41 d1l00313g supervisord: File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 76, in main
Aug 26 05:57:41 d1l00313g supervisord: File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 84, in run
Aug 26 05:57:41 d1l00313g supervisord: File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 117, in add_process_group
Aug 26 05:57:41 d1l00313g supervisord: File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 2041, in make_group
Aug 26 05:57:41 d1l00313g supervisord: ImportError: No module named process
Aug 26 05:57:41 d1l00313g systemd: supervisord.service: control process exited, code=exited status=1
Aug 26 05:57:41 d1l00313g systemd: Failed to start Supervisor process control system for UNIX.
Aug 26 05:57:41 d1l00313g systemd: Unit supervisord.service entered failed state.
Aug 26 05:57:41 d1l00313g systemd: supervisord.service failed
```

Team any help on this issue

**Comment by mnaberez** [comment] 2019-09-01 18:08
Traceback from above reformatted:

> ```
> Traceback (most recent call last):
> File "/usr/bin/supervisord", line 9, in <module>
> load_entry_point('supervisor==4.0.4', 'console_scripts', 'supervisord')()
> File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 358, in main
> File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 368, in go
> File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 76, in main
> File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 84, in run
> File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 117, in add_process_group
> File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 2041, in make_group
> ImportError: No module named process
> ```

**Comment by mnaberez** [comment] 2019-09-01 18:22
The error is being raised from [this line](https://github.com/Supervisor/supervisor/blob/4.0.4/supervisor/options.py#L2041):

    from supervisor.process import FastCGIProcessGroup

Trying that same import from a Python shell succeeds:

```
$ python2
Python 2.7.16 (default, May 19 2019, 14:12:41) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from supervisor.process import FastCGIProcessGroup
>>>
```

I am also not able to reproduce the traceback when running `supervisord` with an `[fcgi-program]` section in the config file.  

This problem is being caused by a broken installation of Supervisor somehow, but I'm not sure how it happened or how to fix it.  The `process.py` file exists so importing it should never fail, and it does not fail on a good installation.  I'm going to close this issue because it seems to be a problem specific on this system rather than a bug in Supervisor itself.

**Closed by mnaberez** 2019-09-01 18:22 UTC

**Comment by tkaya-ipsi** [comment] 2022-06-29 05:24
must be due to file/folder permissions!
