### ISSUE TITLE
Docs: missing information

### ISSUE THREAD

**Issue by rvanlaar** [Supervisor/supervisor#745] opened 2016-04-22 18:11 UTC
I'm missing information in the documentation of supervisord.

A list of available actions commands and what they do
and information where the source and issue tracker can be found.

I had to scurry through the docs to find a link to PyPi.

**Comment by mnaberez** [comment] 2016-04-23 01:10
Duplicate of #250.

**Closed by mnaberez** 2016-04-23 01:10 UTC
Labels: docs, supervisorctl
