### ISSUE TITLE
Add timestamp option to supersivor log

### ISSUE THREAD

**Issue by samirop** [Supervisor/supervisor#1002] opened 2017-10-12 17:16 UTC
It would be pretty helpful to add a timestamp in supervisor logs. 
Sorry if it's already done but I've looked through your documentation + issues and I couldn't find anything related to it.
Thanks in advance

**Comment by mnaberez** [comment] 2017-10-12 17:30
Duplicate of #553

**Closed by mnaberez** 2017-10-12 17:30 UTC
Labels: logging
