### ISSUE TITLE
tags for processes

### ISSUE THREAD

**Issue by RoeyPrat** [Supervisor/supervisor#1026] opened 2017-12-01 09:16 UTC
process grouping is awesome. however it lacks in 2 ways:

1. each process may belong to only 1 group. 
if you have a group of python processes, and a group of processes that serve http, an http serving python process may only belong to one of these groups. 
2. when assigning a process to a group, you de facto change the name of the process.
 if you have scripts that assume a certain name, you have to change them to include group name.

so i suggest adding process tags.
each process may belong to 0 or more tags.
for instance, an http serving python process will have tags:
`[{'language': 'python', {'serves_http': True}]`

**Comment by mnaberez** [comment] 2017-12-01 17:01
Duplicate of #556

**Closed by mnaberez** 2017-12-01 17:01 UTC
