### ISSUE TITLE
Reread/restart/update is still confusing

### ISSUE THREAD

**Issue by AlekSi** [Supervisor/supervisor#1264] opened 2019-08-05 17:10 UTC
It is somewhat a continuation of #720 that is closed but contains comments from a lot of confused people.

### My problem

I need to restart service X exactly once after its package is updated. It contains service binary and a part of supervisord configuration that is `include`-ed from the main file.

### My attempts

1. `supervisorctl update` does not restart service if configuration file did not change, old binary is still running.
2. `supervisorctl restart` restarts service with the old configuration, the new configuration is not used.
3. `supervisorctl reread && supervisorctl restart` does the same as the one above – and that is very surprising!
4. `supervisorctl update && supervisorctl restart` restarts service twice if configuration file changed.

### My solution

```sh
supervisorctl reread

supervisorctl stop X
supervisorctl remove X
supervisorctl add X  # that also starts X as I have `autostart = true` in configuration
```

That works. But is it really the best way? 
And why attempt 3 did not work?

**Comment by mnaberez** [comment] 2019-08-23 19:14
Duplicate of #720.  Please do not open new issues to draw attention to existing issues.  We are reading the existing issues.

**Closed by mnaberez** 2019-08-23 19:14 UTC

**Comment by AlekSi** [comment] 2019-08-23 19:27
I’m sorry, but that existing issue is closed. Does it mean you don’t consider that issue to be an issue?

**Comment by mnaberez** [comment] 2019-08-23 20:34
Correct
