### ISSUE TITLE
[DEFAULT] conf section not supported by supervisord

### ISSUE THREAD

**Issue by vitaly-krugl** [Supervisor/supervisor#1192] opened 2019-01-13 00:14 UTC
To reduce the likelihood of errors when referring to common (shared) value in multiple subsections of the `supervisord.conf` file, I placed them in the `[DEFAULT]` section so that I can use them in the conf file interpolation (as suggested in https://docs.python.org/2.7/library/configparser.html).

However, when I tried running `supervisord -c ./supervisord.conf` with those values in the .conf file, supervisord errored out with "Error: Format string '%(base_log_dir)s/cdho-supervisord.log' for 'supervisord.logfile' contains names ('base_log_dir') which cannot be expanded. ". Here is the complete file:
```
Error: Format string '%(base_log_dir)s/cdho-supervisord.log' for 'supervisord.logfile' contains names ('base_log_dir') which cannot be expanded. Available names: ENV_Apple_PubSub_Socket_Render, ENV_BASH_FUNC_ace_docker_start%%, ENV_BASH_FUNC_dbatt_delete_data_dev%%, ENV_BASH_FUNC_dbatt_delete_dev%%, ENV_BASH_FUNC_dbatt_delete_key_dev%%, ENV_BASH_FUNC_dbatt_delete_key_production%%, ENV_BASH_FUNC_dbatt_delete_key_qa%%, ENV_BASH_FUNC_dbatt_delete_production%%, ENV_BASH_FUNC_dbatt_delete_qa%%, ENV_BASH_FUNC_dbatt_export_backup_dev%%, ENV_BASH_FUNC_dbatt_export_backup_production%%, ENV_BASH_FUNC_dbatt_export_backup_qa%%, ENV_BASH_FUNC_dbatt_override_dev%%, ENV_BASH_FUNC_dbatt_override_production%%, ENV_BASH_FUNC_dbatt_override_qa%%, ENV_BASH_FUNC_dbatt_query_dev%%, ENV_BASH_FUNC_dbatt_query_key_dev%%, ENV_BASH_FUNC_dbatt_query_key_production%%, ENV_BASH_FUNC_dbatt_query_key_qa%%, ENV_BASH_FUNC_dbatt_query_keys_only_dev%%, ENV_BASH_FUNC_dbatt_query_keys_only_production%%, ENV_BASH_FUNC_dbatt_query_keys_only_qa%%, ENV_BASH_FUNC_dbatt_query_override_dev%%, ENV_BASH_FUNC_dbatt_query_override_production%%, ENV_BASH_FUNC_dbatt_query_override_qa%%, ENV_BASH_FUNC_dbatt_query_production%%, ENV_BASH_FUNC_dbatt_query_qa%%, ENV_BASH_FUNC_dbatt_save_dev%%, ENV_BASH_FUNC_dbatt_save_production%%, ENV_BASH_FUNC_dbatt_save_qa%%, ENV_BASH_FUNC_dbatt_search_backup%%, ENV_BASH_FUNC_dbtables_dev%%, ENV_BASH_FUNC_dbtables_production%%, ENV_BASH_FUNC_dbtables_qa%%, ENV_BASH_FUNC_token%%, ENV_GIT_PS1_SHOWDIRTYSTATE, ENV_HOME, ENV_LANG, ENV_LOGNAME, ENV_OLDPWD, ENV_P4CLIENT, ENV_P4CONFIG, ENV_P4EDITOR, ENV_P4PORT, ENV_PATH, ENV_PS1, ENV_PWD, ENV_SHELL, ENV_SHLVL, ENV_SSH_AUTH_SOCK, ENV_TERM, ENV_TERM_PROGRAM, ENV_TERM_PROGRAM_VERSION, ENV_TERM_SESSION_ID, ENV_TMPDIR, ENV_USER, ENV_XPC_FLAGS, ENV_XPC_SERVICE_NAME, ENV__, ENV___CF_USER_TEXT_ENCODING, ENV_dbatt_import_export_root, ENV_dev_cert, ENV_dev_key, ENV_prod_cert, ENV_prod_key, ENV_qa_cert, ENV_qa_key, here
For help, use /usr/local/bin/supervisord -h
```

Here are the salient contents of my supervisord.conf file with everything else redacted:
```
[DEFAULT]
base_log_dir = /Users/me/logs/my-app

[supervisord]
logfile = %(base_log_dir)s/supervisord.log

[program:rest-api]
stdout_logfile = %(base_log_dir)s/cdho-%(program_name)s.log
```

**Comment by mnaberez** [comment] 2019-01-13 18:17
Duplicate of #137

**Closed by mnaberez** 2019-01-13 18:17 UTC
