### ISSUE TITLE
supervisor is marked as python2-only on the python wall of superpowers

### ISSUE THREAD

**Issue by deronnax** [Supervisor/supervisor#573] opened 2015-02-09 11:12 UTC
Supervisor is listed as one of the rare python2-only software on the python wall of superpowers (previously "of shame") (https://python3wos.appspot.com/), whereas the Readme says supervisor runs fine on python3. You should update your tags in setup.py as explained on python3wos.

**Comment by mnaberez** [comment] 2015-02-09 16:25
Duplicate of #510.

**Closed by mnaberez** 2015-02-09 16:25 UTC
Labels: python 3
