### ISSUE TITLE
Killing systemd managed supervisord and immediately restarting fails--XMLRPC race condition?

### ISSUE THREAD

**Issue by acannon828** [Supervisor/supervisor#1041] opened 2018-01-11 16:15 UTC
i.e.:

```
[15:52:39] ip-10-0-12-162:/etc$ sudo systemctl start supervisor; sleep 5; pgrep supervisord | xargs -I{} sudo kill {}; sudo supervisord -e debug; sudo supervisorctl status
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
error: <class 'xmlrpclib.Fault'>, <Fault 6: 'SHUTDOWN_STATE'>: file: /usr/lib/python2.7/xmlrpclib.py line: 800
```

This is not the case when the supervisord process is not managed by systemd, e.g.:

```
/etc$ sudo supervisord -e debug; sleep 5; pgrep supervisord | xargs -I{} sudo kill {}; sudo supervisord -e debug; sudo supervisorctl status
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
foo                              STARTING
```

I can also bypass the error if I `sleep 1` in between killing (the systemd managed supervisord process) and starting another supervisord process:

```
/etc$ sudo systemctl start supervisor; sleep 5; pgrep supervisord | xargs -I{} sudo kill {}; sleep 1; sudo supervisord -e debug; sudo supervisorctl status
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
foo                              STARTING
```

If I remove the call to supervisorctl shutdown specified in the `ExecStop=` in the supervisor.service systemd file (as below), I also no longer see this error indicating the shutdown call is potentially to blame somehow here:

```
[Unit]
Description=Supervisor process control system for UNIX
Documentation=http://supervisord.org
After=network.target

[Service]
ExecStart=/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
ExecStop=/usr/bin/supervisorctl $OPTIONS shutdown
ExecReload=/usr/bin/supervisorctl -c /etc/supervisor/supervisord.conf $OPTIONS reload
KillMode=process
Restart=on-failure
RestartSec=50s

[Install]
WantedBy=multi-user.target
```

...but interestingly enough, if I call `shutdown` and then immediately restart a supervisord process not managed by systemd I don't get the error:

```
etc$ sudo supervisord -e debug; sleep 10; sudo supervisorctl shutdown; sudo supervisord -e debug; sudo supervisorctl status;
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Shut down
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
foo                              STARTING
```

**I'm pretty sure this is what is happening, though I don't follow enough of the XMLRPC code to verify it, can anyone else?**

1. Supervisord process killed
2. Shutdown called (via systemd's ExecStop=)
3. New supervisord process is started, with new XMLRPC server
4. Shutdown signal is sent to the new XMLRPC server, shutting down the new supervisord process

https://github.com/Supervisor/supervisor/issues/48 is almost certainly related.

Ubuntu 16.0.4.3 LTS, supervisor 3.2.0

**Comment by mnaberez** [comment] 2018-01-11 17:45
Duplicate of #48

**Closed by mnaberez** 2018-01-11 17:45 UTC
