### ISSUE TITLE
Remove /tmp/supervisor.sock from sample.conf

### ISSUE THREAD

**Issue by klahnakoski** [Supervisor/supervisor#1238] opened 2019-05-02 22:32 UTC
The `supervisor/skel/sample.conf` has two lines that refer to `/tmp/supervisor.sock`:

```
file=/tmp/supervisor.sock   ; the path to the socket file
```

and

```
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket
```

This is a dangerous place for a file; I find my new linux distros (in Amazon) are removing this file after some period of time.  https://github.com/Supervisor/supervisor/issues/1105

Please change this to `/etc/supervisor.sock`, or some other safer place.

**Comment by mnaberez** [comment] 2019-05-03 00:30
Duplicate of #1105 (exact duplicate of https://github.com/Supervisor/supervisor/issues/1105#issuecomment-488851656)

Please do not open new issues to draw attention to existing issues.  We are reading the existing issues.

**Closed by mnaberez** 2019-05-03 00:30 UTC

**Comment by mrx23dot** [comment] 2026-07-25 11:39
Still not fixed in 2026..
