### ISSUE TITLE
Start more processes

### ISSUE THREAD

**Issue by mindojo-victor** [Supervisor/supervisor#1035] opened 2018-01-01 16:21 UTC
I have this kind of conf:
```ini
[program:brain]
...
numprocs = 1
process_name = %(program_name)s_%(process_num)02d
```
So I am running by default one instance of the process. But I want to be able to start more. But how?
```bash
$ supervisorctl status
brain:brain_00                   RUNNING   pid 43275, uptime 0:00:08

$ supervisorctl start brain:brain_01
brain:brain_01: ERROR (no such process)
```
Is it possible?

**Comment by mnaberez** [comment] 2018-01-01 17:57
Duplicate of #177

**Closed by mnaberez** 2018-01-01 17:57 UTC
Labels: question
