### ISSUE TITLE
Order matters in program section?

### ISSUE THREAD

**Issue by acidjunk** [Supervisor/supervisor#894] opened 2017-02-22 14:34 UTC
We are using supervisord to start celery. It works like a charm. Some celery queues need to be started from a specific working dir so we added "directory" to our supervisor config. Supervisord failed to start the worker. After some experiments and a lot of googling we found that swapping the "command" and the "directory" statements had an effect. E.g. the "directory" statement needs to occur before "command".   

http://stackoverflow.com/questions/23838306/supervisor-directory-not-propagated-to-celery-program

Is this expected behaviour? then a small note in the docs could come in handy

**Comment by acidjunk** [comment] 2017-02-22 14:36
I forgot to add version: we are running supervisord 3.1.3

**Comment by mnaberez** [comment] 2017-03-01 03:09
> After some experiments and a lot of googling we found that swapping the "command" and the "directory" statements had an effect. 

Here's a minimal `supervisord.conf`:

```
[supervisord]
loglevel = debug

[program:pwd]
command = pwd
directory = /tmp/foo
startsecs = 0
autostart = true
autorestart = false
```

Running `supervisord` in the foreground with that config:
```
$ supervisord --version
3.3.1

$ supervisord -n -c supervisord.conf 
2017-02-28 19:05:24,264 INFO Increased RLIMIT_NOFILE limit to 1024
2017-02-28 19:05:24,268 INFO supervisord started with pid 16736
2017-02-28 19:05:25,274 INFO spawned: 'pwd' with pid 16739
2017-02-28 19:05:25,285 DEBG 'pwd' stdout output:
/tmp/foo

2017-02-28 19:05:25,285 INFO success: pwd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-02-28 19:05:25,285 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 4546134960 for <Subprocess at 4546136760 with name pwd in state RUNNING> (stderr)>
2017-02-28 19:05:25,286 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 4546136616 for <Subprocess at 4546136760 with name pwd in state RUNNING> (stdout)>
2017-02-28 19:05:25,286 INFO exited: pwd (exit status 0; expected)
2017-02-28 19:05:25,286 DEBG received SIGCHLD indicating a child quit
```

If I modify the config file above to swap `command=` and `directory=`, the results are the same.  `pwd` always prints the expected directory.

I'm going to close this issue since I can't duplicate it.  If you can provide reproduce instructions similar to the above that shows order matters, we can reopen.

**Closed by mnaberez** 2017-03-01 03:09 UTC
